<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select a color_boldPurple</name>
   <tag></tag>
   <elementGuidId>5ffe89ee-a3d1-4ca9-bbf5-353ea3c4e2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[43]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.zzAcsDqvFnUJt7.rssO3kfwcyxU4I.color-blind-pattern-purple.ybVBgfOiuWZJtD._St8_YSRMkLv07</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;color-tile-purple_dark&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7a32899-abf1-41cc-8860-6519b742111c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zzAcsDqvFnUJt7 rssO3kfwcyxU4I color-blind-pattern-purple ybVBgfOiuWZJtD _St8_YSRMkLv07</value>
      <webElementGuid>a30cc356-5f6e-4187-9496-7fe7e8f320c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>304db523-f936-4959-b206-92ff57db8740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>color-tile-purple_dark</value>
      <webElementGuid>4c90d926-92d8-4e17-8af9-39f153b706f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>bold purple</value>
      <webElementGuid>0acd8cfc-4e2b-471f-8c86-ba28f1f890d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eac53452-619e-425b-b3ba-a49f1d82df4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5aa6f0e9-d07a-418c-98fe-bddc67c56d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>54val-tooltip</value>
      <webElementGuid>abfef8aa-9e4e-47d6-af80-60e08e249dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;feplat3731&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw _9gVZKx4ZK5x4I js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM BxnW01nt1ospt1 YzL7yRijWxDng8&quot;]/div[@class=&quot;rdF_CdqSD31pjK&quot;]/section[@class=&quot;mgn8Z23aXE6pCQ&quot;]/div[3]/div[1]/div[@class=&quot;CVFbGjKC4B_y3v&quot;]/ul[@class=&quot;pryDEk8PiI3MFK Jn1NwCIVwIlwvG&quot;]/li[@class=&quot;CN2trtwQqgYiNl&quot;]/button[@class=&quot;zzAcsDqvFnUJt7 rssO3kfwcyxU4I color-blind-pattern-purple ybVBgfOiuWZJtD _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>0759537c-23df-43d1-8776-622a0dfccc25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[43]</value>
      <webElementGuid>55f47466-ec57-40df-a9fb-d6669b0b73d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/button</value>
      <webElementGuid>781eb348-f34d-466b-b248-b291a39db739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>a81492fb-e5b5-49f8-bd55-b5659797e52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
