<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Name_card-copy-name_13</name>
   <tag></tag>
   <elementGuidId>770f5e57-ea83-4342-b64b-070dc26829cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-copy-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='card-copy-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-copy-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4537cc3a-994f-47f8-9497-3ae723d76ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-copy-textarea</value>
      <webElementGuid>ce21919f-d618-4a39-9089-16142adc3b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-copy-name</value>
      <webElementGuid>99b0dbef-1049-4464-be07-72ec862ab2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>dbb154db-99f0-42d1-9b3d-0e2992600f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fcf1edbd-137c-4a35-b2bf-83e1e89c9c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_zuMQT5LDymvSk</value>
      <webElementGuid>18714509-c836-4ca1-87f2-de003a03594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thẻ này </value>
      <webElementGuid>551dc1b5-6359-4f6b-9249-0cbb4e3e3934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-copy-name&quot;)</value>
      <webElementGuid>3d05956f-9311-4ec4-b878-caedefc51969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='card-copy-name']</value>
      <webElementGuid>eb22c7db-24e9-4aff-88aa-c1586c3fba8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>a1299cb6-5aa3-4af4-bb7c-198ad15ce2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[3]/following::textarea[1]</value>
      <webElementGuid>473b34fc-00ed-4423-b846-f0fb29c777ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy to…'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c36e8f8f-d1ac-4c76-998f-59c14d7e808f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[4]/preceding::textarea[1]</value>
      <webElementGuid>e2d6db15-39b5-468b-8860-44d6b5c57cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thẻ này']/parent::*</value>
      <webElementGuid>6e7413ad-11ce-4ec0-b96c-0b4a7be1ca4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>2c27162e-c285-4f76-bede-5209f24f60ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Thẻ này ' or . = 'Thẻ này ')]</value>
      <webElementGuid>f7976302-787b-44be-9de9-da724fe7202b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The·']/parent::*</value>
      <webElementGuid>cd7d2631-3734-436c-8b4f-2b55d735035c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'The·' or . = 'The·')]</value>
      <webElementGuid>49c4bfd6-6238-454d-b6a1-63c4063ab8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
