<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Name_card-copy-name_33</name>
   <tag></tag>
   <elementGuidId>9ac8f1c9-d281-4113-ac27-e045c1668b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-copy-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='card-copy-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-copy-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>21477994-ada1-4f13-a51e-1d73268225c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-copy-textarea</value>
      <webElementGuid>0feeedea-90e6-49ac-b3da-5044874ac741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-copy-name</value>
      <webElementGuid>e8388798-81d1-4d9c-98e1-144930081a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>ddbbe65c-16ee-4b3f-b120-68bc9bd308be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>43d5c013-6c0a-4414-9c14-9a999bd86643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_zuMQT5LDymvSk</value>
      <webElementGuid>1b031353-30ac-41cb-86da-6446f1570443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thẻ này là th</value>
      <webElementGuid>c90e5ff1-adf8-4783-aa4a-8d6f46fd566f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-copy-name&quot;)</value>
      <webElementGuid>3b891798-3428-4684-9319-29def0ea09e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='card-copy-name']</value>
      <webElementGuid>a5603f36-2b2e-48b1-b9f1-ce00468f2e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>43d6d3e8-6e09-4147-9572-16f37075f512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[3]/following::textarea[1]</value>
      <webElementGuid>8ded591b-fdba-4f9c-ab44-d632e5f9df37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy to…'])[1]/preceding::textarea[1]</value>
      <webElementGuid>90e63435-b771-4ab8-8ca7-9fb24c010bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[4]/preceding::textarea[1]</value>
      <webElementGuid>bb367fa7-cb74-4ac5-a8f5-af96ae630280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thẻ này là th']/parent::*</value>
      <webElementGuid>e33f3e0a-324d-4088-a18e-383156e0b179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>53dd187b-4001-4ae1-9605-3254960d58e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Thẻ này là th' or . = 'Thẻ này là th')]</value>
      <webElementGuid>8d32adba-c3c2-4914-874d-45b7cc137f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
