<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Them the moi_QnC5HZJq_5Juhe_8</name>
   <tag></tag>
   <elementGuidId>3273186a-3398-4f06-8093-89c4f0c84015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.QnC5HZJq_5Juhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;list-card-composer-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9983f732-25c8-45dc-8695-1d411a4f925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-card-composer-textarea</value>
      <webElementGuid>7393ae98-f282-44ab-9e8f-9bf193f7bf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QnC5HZJq_5Juhe</value>
      <webElementGuid>0dd79927-7146-41c5-8ee6-9a8420ad01f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c76fabba-eb29-4b33-8c45-be6272117861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title or paste a link</value>
      <webElementGuid>8e285275-3426-4fb5-9673-a1041c358ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Theem the</value>
      <webElementGuid>4be34ec2-92e1-4784-9f9d-c1d2a005d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;cp7mT8xGYhMPie&quot;]/form[1]/textarea[@class=&quot;QnC5HZJq_5Juhe&quot;]</value>
      <webElementGuid>6e7ed944-2b47-4b47-8323-681b47709087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      <webElementGuid>e782013c-3b68-4dce-8065-c49578a04f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Them the moi'])[1]/following::textarea[1]</value>
      <webElementGuid>ee38436d-9070-42d3-a173-2972a05acd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start using Trello'])[1]/following::textarea[1]</value>
      <webElementGuid>fd9a900e-7004-4f97-9089-02aa40bb4e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add card'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c4e86f62-3b4d-4cee-8f62-4fea2109fab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::textarea[1]</value>
      <webElementGuid>078b5b0f-851b-438c-bde2-799a2ea55718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Theem the']/parent::*</value>
      <webElementGuid>f1032e12-2aeb-44c7-8c34-b4419b5907d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>c61c6c8d-cc17-47b7-a2a4-43546a392b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Theem the' or . = 'Theem the')]</value>
      <webElementGuid>05799bf4-4d84-47c2-b3a3-0e4d33ecb8e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
