<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Kim th Trello_QnC5HZJq_5Juhe_3</name>
   <tag></tag>
   <elementGuidId>50ed8cad-bd21-47c4-be5d-54e76698f561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.QnC5HZJq_5Juhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[3]/div/ol/li/form/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;list-card-composer-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a857d98d-88cf-4e9e-a765-7623f80561e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-card-composer-textarea</value>
      <webElementGuid>dde1a699-f066-4fd1-a1aa-78732f039e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QnC5HZJq_5Juhe</value>
      <webElementGuid>22fe9673-23f2-4e40-a097-1c5046791ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>294cc1c7-cea6-4b14-b19d-09f6f91c321c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title or paste a link</value>
      <webElementGuid>4e5f26a4-64ea-4d23-b085-67df3b3e417c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The·</value>
      <webElementGuid>fd547f0c-ae66-478f-be55-54f26c64c936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;cp7mT8xGYhMPie&quot;]/form[1]/textarea[@class=&quot;QnC5HZJq_5Juhe&quot;]</value>
      <webElementGuid>cb46c32e-1b96-4365-be20-42456d6a2468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[3]/div/ol/li/form/textarea</value>
      <webElementGuid>55ab76bd-e4af-44ea-9c17-8476be2f7dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[2]/following::textarea[1]</value>
      <webElementGuid>75098b83-4f3b-4934-b601-4ba6733f0525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[1]/following::textarea[2]</value>
      <webElementGuid>e8427c3b-4f63-4eee-9e6c-ff304051e99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add card'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8e0376cf-4887-473b-94d6-cc56bbea4e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Later'])[1]/preceding::textarea[1]</value>
      <webElementGuid>26f9acfc-ca81-490e-af6f-a7fdef7581ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The·']/parent::*</value>
      <webElementGuid>2e827a9e-e257-4308-8af3-a9d14dedda55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>7655cadb-3b7d-4864-8e77-7c00f433ca04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'The·' or . = 'The·')]</value>
      <webElementGuid>1edb818c-a4d4-4265-8dd0-53bf3e87d470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li/form/textarea</value>
      <webElementGuid>3e2db453-9dfe-4fe2-a194-c58147a6ee85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử Trello'])[2]/following::textarea[1]</value>
      <webElementGuid>1417faaa-6e8f-4d83-860c-0346c5565d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử Trello'])[1]/following::textarea[2]</value>
      <webElementGuid>bd70a254-7b46-42f1-bf2a-6fe10672872e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9c3887eb-7479-437f-a36a-34221f4cd291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>23c590be-76bc-4a10-a338-3a7e384f0f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>109b3350-4a34-4d0c-a1c4-0e3805fcfae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
