<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Atlassian_UXFQgc</name>
   <tag></tag>
   <elementGuidId>8cf8744d-5ae8-47fb-b758-11b067206662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.UXFQgc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yDmH0d']/c-wiz/main/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d84bd0fc-3b67-4893-8623-1844d2e747ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UXFQgc</value>
      <webElementGuid>dff7f14b-a585-450a-a3ac-ec0597f18737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>uybdVe</value>
      <webElementGuid>d3e16d0b-4c5e-427d-bb3b-463f867ad6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email or phoneForgot email?Type the text you hear or see</value>
      <webElementGuid>311de312-6fcf-4b46-b4e9-cb16c0be74f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;A77ntc&quot;]/main[@class=&quot;Svhjgc&quot;]/div[@class=&quot;UXFQgc&quot;]</value>
      <webElementGuid>243de79e-4204-4e21-a7c7-8af414072503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/main/div[2]</value>
      <webElementGuid>c1e88d98-1a0d-4380-a474-e64918bc2372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlassian'])[1]/following::div[1]</value>
      <webElementGuid>70891243-67cc-4016-94bd-07ab43179bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[43]</value>
      <webElementGuid>d1d6916a-0d6e-44de-9147-4e23125b49de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]</value>
      <webElementGuid>a117ef87-eb35-4104-a1ff-c9440054764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email or phoneForgot email?Type the text you hear or see' or . = 'Email or phoneForgot email?Type the text you hear or see')]</value>
      <webElementGuid>af610889-9d2e-4049-a880-0c1d76e3cff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
