<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_edit_workspace</name>
   <tag></tag>
   <elementGuidId>118eac40-a50b-4d78-9d95-71679b416a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dD63crzZphvph6.ybVBgfOiuWZJtD.mUpWqmjL4CZBvn._St8_YSRMkLv07 > span.nch-icon.hChYpzFshATQo8.GzZMAuibTh5l1i > span._1e0c1o8l._1o9zidpf._vyfuvuon._vwz4kb7n._1szv15vq._1tly15vq._rzyw1osq._17jb1osq._1ksvoz0e._3se1x1jp._re2rglyw._1veoyfq0._1kg81r31._jcxd1r8n._gq0g1onz._1trkwc43</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/main/main/div/div/div/div[2]/h2/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3046d55a-b09e-40c9-b6b9-aa7221c2138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>EditIcon</value>
      <webElementGuid>56b86d52-013b-4e8f-9513-68883bab9d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vc</name>
      <type>Main</type>
      <value>icon-EditIcon</value>
      <webElementGuid>74f61ebb-c162-4298-833a-4916d4a439ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a35fc50-df9b-49aa-8c74-abc4b74f5c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1e0c1o8l _1o9zidpf _vyfuvuon _vwz4kb7n _1szv15vq _1tly15vq _rzyw1osq _17jb1osq _1ksvoz0e _3se1x1jp _re2rglyw _1veoyfq0 _1kg81r31 _jcxd1r8n _gq0g1onz _1trkwc43</value>
      <webElementGuid>fd3e654e-bf6d-460d-b947-2f364eb1ac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;gWf80FmcNO65Hd&quot;]/main[@class=&quot;hIlbOkoIOozQ23&quot;]/main[1]/div[@class=&quot;k7DVPxTJAD6qiD VyqU0BLtvqgIlS&quot;]/div[1]/div[@class=&quot;seZQsl0rcZEnv0&quot;]/div[@class=&quot;NM0plCEO3t86Fq&quot;]/h2[@class=&quot;j4Z_Z_KQ9v0zga&quot;]/button[@class=&quot;dD63crzZphvph6 ybVBgfOiuWZJtD mUpWqmjL4CZBvn _St8_YSRMkLv07&quot;]/span[@class=&quot;nch-icon hChYpzFshATQo8 GzZMAuibTh5l1i&quot;]/span[@class=&quot;_1e0c1o8l _1o9zidpf _vyfuvuon _vwz4kb7n _1szv15vq _1tly15vq _rzyw1osq _17jb1osq _1ksvoz0e _3se1x1jp _re2rglyw _1veoyfq0 _1kg81r31 _jcxd1r8n _gq0g1onz _1trkwc43&quot;]</value>
      <webElementGuid>e194a192-927d-49b9-a61f-65ab84ba9a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/main/main/div/div/div/div[2]/h2/button/span/span</value>
      <webElementGuid>06037156-c296-4351-8ec4-ce36a3258a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change logo'])[1]/following::span[2]</value>
      <webElementGuid>2255b16d-17c9-4e35-8578-bacfaeec78b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::span[1]</value>
      <webElementGuid>13cb1489-f11d-477b-a552-089e4f8c071b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspace visibility'])[1]/preceding::span[4]</value>
      <webElementGuid>f44e3029-d262-4783-a9e8-23f7e8484833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/button/span/span</value>
      <webElementGuid>72785789-af9a-4e54-8db5-801d471252e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
