<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Featured_WGY9hGsS5muj12 oVTy_5Hj0NsJON</name>
   <tag></tag>
   <elementGuidId>5e8c8e3b-6c22-44f6-9d31-4b2387f298cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.WGY9hGsS5muj12.oVTy_5Hj0NsJON</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trello-board-root']/div/div/div/div[2]/div/div[2]/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5eacc25c-497e-4302-af0d-c0da7ccb4fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/b/E8hluBPy/datvexemphim/power-ups/enabled</value>
      <webElementGuid>328e7fbe-af6d-4832-a2e6-6950b685b679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WGY9hGsS5muj12 oVTy_5Hj0NsJON</value>
      <webElementGuid>b913427e-5b92-416a-9e5b-31e621fcb5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>enabled-powerups-link</value>
      <webElementGuid>f8a35688-ceba-47e8-bd1b-e7224e7d99d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enabled2</value>
      <webElementGuid>a6a461cd-5eb3-45f2-a398-f33c176c45da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trello-board-root&quot;)/div[1]/div[@class=&quot;board-wrapper&quot;]/div[@class=&quot;board-main-content MGBVHMvOK1TD8j Xpq6bBra11ICMi ivZ_wF4VZB8iYB&quot;]/div[@class=&quot;board-canvas&quot;]/div[@class=&quot;u9fbqAqsZm2m8M&quot;]/div[@class=&quot;z4R6o22U1TiJyR&quot;]/div[@class=&quot;Xw8Tg1DihmxOH0&quot;]/div[@class=&quot;aIZlg_Z9MmRARS&quot;]/ul[1]/li[2]/a[@class=&quot;WGY9hGsS5muj12 oVTy_5Hj0NsJON&quot;]</value>
      <webElementGuid>e3fa4918-29be-44c0-a51b-64718b3211a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trello-board-root']/div/div/div/div[2]/div/div[2]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>643098c9-43ce-4049-b74a-48d3f1434056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured'])[1]/following::a[1]</value>
      <webElementGuid>02ddc8d3-27c5-4720-92fa-b8a075d035ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[2]</value>
      <webElementGuid>1e52a76d-3329-4085-9814-f522d34bffda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made by Trello'])[2]/preceding::a[1]</value>
      <webElementGuid>1329f90c-174d-41d4-9b20-4b5b6d7d7352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::a[2]</value>
      <webElementGuid>7dad5b38-0de1-4f09-8e0b-74f436ab8c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enabled']/parent::*</value>
      <webElementGuid>56fd888e-996e-47e5-bfe3-c05a57e56c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/b/E8hluBPy/datvexemphim/power-ups/enabled')]</value>
      <webElementGuid>d0337546-3054-4f54-854d-98100ac0c940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]/a</value>
      <webElementGuid>4632e466-2d10-4c47-8ad1-1e37785ba6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/b/E8hluBPy/datvexemphim/power-ups/enabled' and (text() = 'Enabled2' or . = 'Enabled2')]</value>
      <webElementGuid>30759b82-0820-47b5-af85-bce8b5989c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made by Trello'])[1]/preceding::a[1]</value>
      <webElementGuid>55129ba9-6acf-4540-a461-225e4f70161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/b/E8hluBPy/datvexemphim/power-ups/enabled' and (text() = 'Enabled3' or . = 'Enabled3')]</value>
      <webElementGuid>24e0ae4b-aeb6-4021-a65c-a6298f8e2236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/b/E8hluBPy/datvexemphim/power-ups/enabled' and (text() = 'Enabled4' or . = 'Enabled4')]</value>
      <webElementGuid>2f3a5ecb-2b46-4c4e-add8-cf1391972ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
