<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi_QnC5HZJq_5Juhe_19</name>
   <tag></tag>
   <elementGuidId>40a81284-fd23-4917-b88f-68f077f4a415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.QnC5HZJq_5Juhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;list-card-composer-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a6500332-e29f-4a3c-a1f9-a278fcdb76d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-card-composer-textarea</value>
      <webElementGuid>30354405-97a9-4013-a2bb-ee5caefe25fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QnC5HZJq_5Juhe</value>
      <webElementGuid>b19dfc01-3b58-42ea-941a-4842f2ec087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>56041bec-9e64-4081-a809-5d9f447cb663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title or paste a link</value>
      <webElementGuid>8b5c67ea-027a-49f2-a1fc-84f109d6e2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm thẻ mơi</value>
      <webElementGuid>95b2fc27-2eeb-44a3-b466-853dc5fa7ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;cp7mT8xGYhMPie&quot;]/form[1]/textarea[@class=&quot;QnC5HZJq_5Juhe&quot;]</value>
      <webElementGuid>45c9ab71-4a64-42ca-b293-1e0121e23ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      <webElementGuid>08e4a5c3-a3ed-4bad-af34-8dbe08ac8825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới'])[1]/following::textarea[1]</value>
      <webElementGuid>45919caa-0d2e-4a9c-8409-a5563e34d504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mơi'])[1]/following::textarea[1]</value>
      <webElementGuid>c600d60f-f73b-407a-9104-b57d8cb15413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add card'])[1]/preceding::textarea[1]</value>
      <webElementGuid>deb3252d-9dd7-4aa7-93bf-0935e2c94c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::textarea[1]</value>
      <webElementGuid>90dc1a38-0123-4f95-b5b4-94d7303f6eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>74fb6340-e729-4c9c-9158-1c9f4d59c5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Thêm thẻ mơi' or . = 'Thêm thẻ mơi')]</value>
      <webElementGuid>a594f353-571b-49df-b9d1-649a76d0b280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[2]/form/textarea</value>
      <webElementGuid>5e879fc7-6cdb-4dac-838f-4c806b78208e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử Trello'])[2]/following::textarea[1]</value>
      <webElementGuid>b61ab282-0ecb-42a0-819b-1e3ab11ca295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm thẻ mơi·']/parent::*</value>
      <webElementGuid>d7321bbb-ba1d-4216-89f8-be17ac10642b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Thêm thẻ mơi·' or . = 'Thêm thẻ mơi·')]</value>
      <webElementGuid>33666e3e-bd5f-4596-ae11-61068c2c672d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
