<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Them the moi_QnC5HZJq_5Juhe_10</name>
   <tag></tag>
   <elementGuidId>6e72b678-8d60-48a3-a378-80eac9c5e30a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.QnC5HZJq_5Juhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;list-card-composer-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b70b1f4c-60a9-4797-a4d4-5c83e98ab048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-card-composer-textarea</value>
      <webElementGuid>57ba6ffc-d7f6-4a4d-bed8-e3cbe88ad995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QnC5HZJq_5Juhe</value>
      <webElementGuid>b375541e-7b45-4a20-897a-1e871ee29c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c4a31910-ce65-4aed-a792-180d7d75856e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title or paste a link</value>
      <webElementGuid>4fc17802-44ba-42ea-a633-fb542eab5580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Theem the m</value>
      <webElementGuid>f750399d-7503-47f3-8123-d42599926dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;cp7mT8xGYhMPie&quot;]/form[1]/textarea[@class=&quot;QnC5HZJq_5Juhe&quot;]</value>
      <webElementGuid>206cdf7f-d6fd-4d9f-a59d-c77fa85f8f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      <webElementGuid>48cccc18-d94a-44c8-a314-622739219ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Them the moi'])[1]/following::textarea[1]</value>
      <webElementGuid>8565e2d8-70fa-4d0a-a7af-3a1e30d0e6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start using Trello'])[1]/following::textarea[1]</value>
      <webElementGuid>11b50c5f-6950-415a-b93e-449e14252edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add card'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a43990eb-71e2-45ac-89b4-9c6e582130e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b8ebc557-d1f8-40f0-ae0d-1b5b29ef9d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Theem the m']/parent::*</value>
      <webElementGuid>213c68bb-7290-4610-8d49-f0efb1ee2acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>5ede7dd7-dba8-469d-ae13-31060a2ef5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Theem the m' or . = 'Theem the m')]</value>
      <webElementGuid>11ae04c0-32f7-465a-be5e-0e2c18600654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
