<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi_QnC5HZJq_5Juhe_6</name>
   <tag></tag>
   <elementGuidId>60d2b6a9-167c-4e17-ad4f-c99118a8aa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.QnC5HZJq_5Juhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;list-card-composer-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1a68b2c6-0a61-4088-85a6-f2d18a7b4d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-card-composer-textarea</value>
      <webElementGuid>20832163-b723-4a88-b800-260bbd6c50b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QnC5HZJq_5Juhe</value>
      <webElementGuid>91d1d639-8d4e-4be2-a820-9c2141e05b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3442a0aa-2db1-40ea-bf05-3cfb7997e934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title or paste a link</value>
      <webElementGuid>38a9f22c-9221-4572-b21c-24586be8cfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm </value>
      <webElementGuid>5f5c6901-c072-48d1-a86b-e9fcc36cc170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;cp7mT8xGYhMPie&quot;]/form[1]/textarea[@class=&quot;QnC5HZJq_5Juhe&quot;]</value>
      <webElementGuid>99c97037-04f2-4417-bc77-7784b1a9f4a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[3]/form/textarea</value>
      <webElementGuid>5dcf47ad-5fc4-45bc-8a18-73b4b8adad7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới'])[1]/following::textarea[1]</value>
      <webElementGuid>0b79815f-beae-48ab-929d-4e74be0654e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mơi'])[1]/following::textarea[1]</value>
      <webElementGuid>d116a97a-5d46-4d48-9f07-daba7cb25afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add card'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4660b864-f484-437a-badc-56a694a23fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a5f75e9c-6d69-40e0-81e7-52250de14fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm']/parent::*</value>
      <webElementGuid>0c9992fd-cb4a-4608-b25a-35e294d7857b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>6c84724d-01c6-4a6c-83e6-9f7540d4e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title or paste a link' and (text() = 'Thêm ' or . = 'Thêm ')]</value>
      <webElementGuid>de8d3ff7-5030-425c-9e9e-9cecd1b0c56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li[2]/form/textarea</value>
      <webElementGuid>c9b54721-6280-4186-a0a2-0379164ac472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử Trello'])[2]/following::textarea[1]</value>
      <webElementGuid>9bbe6f05-309e-4231-9126-49d9bbe4d508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
