<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_add-checkitem-69244ac5b2cea_39c2c6</name>
   <tag></tag>
   <elementGuidId>f4edc881-6548-4b96-9bc9-cdc04747b22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-checkitem-69244ac5b2cea0bbe7318ba3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='add-checkitem-69244ac5b2cea0bbe7318ba3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;check-item-name-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b417392d-c4b0-4edc-9e15-f551992a575a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>check-item-name-input</value>
      <webElementGuid>fc7fdf00-b2b2-4e09-bf0c-f7ba19fec432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add an item</value>
      <webElementGuid>9d2475bb-d83d-4e64-b502-de10f9112b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d206fbfb-ad99-4563-8fb3-0fa6b08e9ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CfQ1Gu9vrIMPLB</value>
      <webElementGuid>805df66b-477e-4a1e-a169-5599a50ed020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add an item</value>
      <webElementGuid>b4322e26-538e-420e-a214-781b910f5888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-checkitem-69244ac5b2cea0bbe7318ba3</value>
      <webElementGuid>5789a161-12b0-44ab-9b51-3790ff6d7e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-checkitem-69244ac5b2cea0bbe7318ba3&quot;)</value>
      <webElementGuid>f4de3791-05a4-46b7-bfc6-a25ae25b43e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='add-checkitem-69244ac5b2cea0bbe7318ba3']</value>
      <webElementGuid>6a37af33-7b79-4837-9d41-72d6295e60fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/div[2]/form/textarea</value>
      <webElementGuid>a1c65a63-140e-4ee6-b78d-06faa4abcdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>0a025751-0b84-42bc-80db-6e959bc3ff0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add an item' and @id = 'add-checkitem-69244ac5b2cea0bbe7318ba3']</value>
      <webElementGuid>b2a87dab-b950-4eb6-891f-738bfab14df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
