<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_Workspace_Type_Item</name>
   <tag></tag>
   <elementGuidId>d42df83c-d7f6-4830-ae3c-e98963d21fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Engineering-IT' or . = 'Engineering-IT')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'menu')]//*[normalize-space(text())='Other']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-option-0 > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1796b771-d45f-49a6-8957-ec3ae1dcae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engineering-IT</value>
      <webElementGuid>65fbdcdf-1877-4691-9e50-e6425ca16c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-option-0&quot;)/li[1]</value>
      <webElementGuid>c3db3262-e70b-4514-aef6-4e87e31e5686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-option-0']/li</value>
      <webElementGuid>03b1a18a-b466-4935-af2f-07d57a944be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process'])[1]/following::li[1]</value>
      <webElementGuid>6381bd20-b6ef-4f1b-8d42-4fabdccbddb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[1]/following::li[1]</value>
      <webElementGuid>71f2894c-48e8-47a8-a416-2cd1ae1bffaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales CRM'])[1]/preceding::li[1]</value>
      <webElementGuid>07ca9f5b-6c99-430f-a80d-b7376f1b488a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/preceding::li[2]</value>
      <webElementGuid>3e51fa6c-c509-405c-b13b-719016a921b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Engineering-IT']/parent::*</value>
      <webElementGuid>f11628be-6a29-41fd-9d34-732c1924d951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>b6d422a7-667a-4a40-8687-c10b633107d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Engineering-IT' or . = 'Engineering-IT')]</value>
      <webElementGuid>bb2dd334-4d82-43b9-9b52-c01c66727383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/preceding::li[1]</value>
      <webElementGuid>2b817b82-f85b-4078-8972-788bc5af0669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales CRM'])[1]/preceding::li[2]</value>
      <webElementGuid>3db7dcad-39ac-4d85-bab0-7bb4f290e80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Small Business']/parent::*</value>
      <webElementGuid>08cd882d-0a42-40f0-8922-a19a14d086c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Small Business' or . = 'Small Business')]</value>
      <webElementGuid>1de770b8-0a99-41af-b8cd-ab4dff6f6bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
