<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Workspace_Description</name>
   <tag></tag>
   <elementGuidId>50890c2e-575e-4666-b7c7-096f2ddb8547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@id,create-team-org-description)]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1764233128446-create-team-org-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>97955d51-96c1-490f-bcf8-f183630d523e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1764233128446-create-team-org-description</value>
      <webElementGuid>475d53dd-1272-404d-b119-8160255951d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d3bfd57a-44ee-4582-b971-f932f149f8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KGRcJEfEKtezf2</value>
      <webElementGuid>2ac620eb-70f6-4fc3-8349-e092958ea863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Our team organizes everything here.</value>
      <webElementGuid>3f3c38f2-9021-40a8-a2df-b81a4cb938e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07fc2608-fb03-4673-8c26-8ec64a2b42b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1764233128446-create-team-org-description&quot;)</value>
      <webElementGuid>7d1bff47-cf90-4ae8-89c6-5b5ae106ed53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='1764233128446-create-team-org-description']</value>
      <webElementGuid>02158540-ec82-40e3-8baf-588585a7606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-overlay']/div/div/div/div/div/form/textarea</value>
      <webElementGuid>5068ea11-7fac-48e6-8cc6-be51629f9bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional'])[1]/following::textarea[1]</value>
      <webElementGuid>b96d905b-d2fa-48d0-a0ce-fff640a58098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your members on board with a few words about your Workspace.'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3f4aa18f-b2aa-4ffa-a148-612f18c9d7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6ad57f59-f250-4e4c-ab43-0192b805cea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f56c2f86-3197-4218-9c88-1f4e8c7edf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '1764233128446-create-team-org-description' and @placeholder = 'Our team organizes everything here.' and (text() = 'a' or . = 'a')]</value>
      <webElementGuid>dd31e7f9-8983-45aa-b048-bc11806b71c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
