<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tWorkspace</name>
   <tag></tag>
   <elementGuidId>0a23be8c-182a-4bcc-b2b5-a32dcb718d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[.//span[@data-testid='home-team-tab-name' and normalize-space(text())='${workspaceName}']]//a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.IyWeSHzb5z4TTx > ul > li.WmhimhrsxjL1KU > a.wNdgQfwraPxaK7 > span.QEGH0t6lsxm4C9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e3904a9-d547-47a3-905d-5df2e454d5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>home-team-tab-name</value>
      <webElementGuid>2791108d-3700-466d-a0ea-78fc445a0448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QEGH0t6lsxm4C9</value>
      <webElementGuid>53748612-ea70-4c0c-87d5-d371a9e981cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfd55782-e066-422e-a14a-a711d3a3897f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/nav[@class=&quot;eOF7HLejybn5ad&quot;]/section[@class=&quot;v2yaj6y7dtFy4C&quot;]/div[1]/section[@class=&quot;IyWeSHzb5z4TTx&quot;]/ul[1]/li[@class=&quot;WmhimhrsxjL1KU&quot;]/a[@class=&quot;wNdgQfwraPxaK7&quot;]/span[@class=&quot;QEGH0t6lsxm4C9&quot;]</value>
      <webElementGuid>1379283e-bfa5-4109-b606-78ce955ee56d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/nav/section/div/section/ul/li/a/span</value>
      <webElementGuid>069fa217-b4a9-4d03-995b-34b9a6739afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::span[1]</value>
      <webElementGuid>53a4071c-24de-4c73-8607-eb05a793f127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspaces'])[1]/following::span[1]</value>
      <webElementGuid>6634e2d1-38d4-4eac-ae62-b18fca0b96ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[2]/preceding::span[4]</value>
      <webElementGuid>06fbff5a-ced2-4631-a409-36b19dc40092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a c'])[1]/preceding::span[4]</value>
      <webElementGuid>5f26542c-4f45-4f93-9f17-4cee1e490999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='a']/parent::*</value>
      <webElementGuid>fcf53bbf-8fbc-4a14-bee5-4536cd384ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/a/span</value>
      <webElementGuid>eb7838bb-f60e-4c9a-921e-f66b222c24d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'a' or . = 'a')]</value>
      <webElementGuid>87d883f9-3f49-43cc-bbf0-09e3f8c0a326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
