<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Doing_LqgHiubcZnMWmo</name>
   <tag></tag>
   <elementGuidId>555de0e0-e8d2-4969-ae25-5dda8b8b76e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.LqgHiubcZnMWmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d253b4f6-7c5f-4951-a8db-6b4bc5aa46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LqgHiubcZnMWmo</value>
      <webElementGuid>8f26cea3-4516-4411-a747-594fce1e5408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-front-cover</value>
      <webElementGuid>2c11bda7-b09c-4849-9ffd-33f54c3753fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-card-front-section</name>
      <type>Main</type>
      <value>cover</value>
      <webElementGuid>4329a127-c4f1-4c4d-bafe-62ba501dfa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LqgHiubcZnMWmo&quot;]</value>
      <webElementGuid>5db85de9-14df-4b1a-87ff-4b78dc4a3e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div</value>
      <webElementGuid>3cdef0ab-f314-4eee-8aad-a9147cc4212f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ol/li/div/div/div</value>
      <webElementGuid>81e1a1ca-aa3b-4a26-852e-fabd5dddcd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
