<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QAQC_LqgHiubcZnMWmo</name>
   <tag></tag>
   <elementGuidId>7ce2db4e-d92d-4054-9b94-2ec6827bdeac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[3]/div/ol/li/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cb407d7-a07e-4916-84e5-2fc0c5131037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LqgHiubcZnMWmo</value>
      <webElementGuid>ba3320e6-7a81-41e1-ad11-4c89f06a8d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-front-cover</value>
      <webElementGuid>3f90fd64-191d-47ef-b75c-72bf6ca2a7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-card-front-section</name>
      <type>Main</type>
      <value>cover</value>
      <webElementGuid>8af673b1-8170-4a79-96e7-7b0d7971666f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LqgHiubcZnMWmo&quot;]</value>
      <webElementGuid>6f57c087-052d-45de-9ea4-faef396ca07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[3]/div/ol/li/div/div/div</value>
      <webElementGuid>d9665441-00e2-45c2-8c23-d1881d5ce62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ol/li/div/div/div</value>
      <webElementGuid>d8b29169-d20a-4ec8-85a4-dd42e0ffc4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
