<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>e1116b49-5651-44da-82e1-302949ac709c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.selected > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97fbf2c0-cf43-47dd-9150-8d795d33a552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a42cfc71-d6b3-47ef-96ef-68895e706147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In 1 hour</value>
      <webElementGuid>b600ebe6-1f33-4111-9474-62bda53f643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[2]/div[1]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[1]/div[1]/div[@class=&quot;js-results&quot;]/ul[@class=&quot;pop-over-list js-list navigable&quot;]/li[@class=&quot;selected&quot;]/a[1]</value>
      <webElementGuid>7ff7e9f9-419e-4fc7-ac66-91f94b74aa67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>04878ec3-79e9-4b79-beb9-7622348cddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'In 1 hour')]</value>
      <webElementGuid>778d1108-891b-4315-be72-47a3b0acedc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Time'])[1]/following::a[1]</value>
      <webElementGuid>aa15fb45-1c8c-4557-a45c-5b98fb986ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Un-snooze Card'])[1]/following::a[3]</value>
      <webElementGuid>93603210-3bc2-41c6-9ef3-3afc57f0cdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In 2 hours'])[1]/preceding::a[1]</value>
      <webElementGuid>6d9a2003-b915-48b0-92b9-aa275355cc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In 4 hours'])[1]/preceding::a[2]</value>
      <webElementGuid>232643f6-b0d0-4d03-8fce-5029853b0a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='In 1 hour']/parent::*</value>
      <webElementGuid>c762b8c6-006f-4557-92b6-db7263ef2d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>64d060f7-aad5-4b0e-9c74-b7c8cb18907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'In 1 hour' or . = 'In 1 hour')]</value>
      <webElementGuid>736bb69c-10c4-4b96-8fe7-a131b4d4a847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
