<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display text (optional)_displayText-uid80</name>
   <tag></tag>
   <elementGuidId>2bfa4932-3553-4b51-ad98-53ec72b04a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayText-uid80</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayText-uid80']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe21875c-6a12-4e85-b42c-bc7c4d84cea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined displayText-uid80-error</value>
      <webElementGuid>1280ad32-40ac-4385-be47-10521366f975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>displayText-uid80-label</value>
      <webElementGuid>e46ea479-742b-4aa6-a51e-0e41d45190d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayText-uid80</value>
      <webElementGuid>1d910e7b-ac13-40a6-ab0e-ce4813d82c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f58c3188-25e8-4d7b-8b3d-b1b449c84f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ds--text-field--input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42e24ddf-3d00-4381-aea2-0d47fd02aee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-text</value>
      <webElementGuid>9ca7d018-b7a2-42fe-905f-d3022e814a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayText</value>
      <webElementGuid>369757e3-51d0-4dd2-88e9-a2b620d52233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text to display</value>
      <webElementGuid>f3be6010-8800-431c-a970-ace8b113e8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_19itidpf _11c82smr _12ji1r31 _1qu2glyw _12y31o36 _vchhusvi _1bsb1osq _1ul9idpf _bfhk1j28 _syaz1kw7 _80om1kw7 _14jiu2gc _olc6u2gc _1kod12x7 _7ba012x7 _1goxglyw _13xeglyw _1n7e1l2s _1idr131l</value>
      <webElementGuid>a1dedd5e-7e4b-4480-9bb6-589826efe35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayText-uid80&quot;)</value>
      <webElementGuid>a5646014-719b-4843-a5ec-c6c95a1c8ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayText-uid80']</value>
      <webElementGuid>843932de-445a-4655-bf2a-630794d7a751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d0f43b8e-7043-4b73-aa95-8aa0780a03b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayText-uid80' and @name = 'displayText' and @placeholder = 'Text to display']</value>
      <webElementGuid>f96ead5a-f641-41a0-a8ec-a01d75094d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
