<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display text (optional)_displayText-uid81</name>
   <tag></tag>
   <elementGuidId>cd91768c-4e25-44c1-94f2-b9ab3d89c507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayText-uid81</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayText-uid81']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52b8d88b-d547-4b0a-9921-e6de8c70492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined displayText-uid81-error</value>
      <webElementGuid>ac578be8-5ed1-4ecb-a29c-ca65e9dec484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>displayText-uid81-label</value>
      <webElementGuid>6cae1ef2-dbc5-4999-b5ae-849ae4024a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayText-uid81</value>
      <webElementGuid>8428d0f3-0b7d-41ca-a251-668cca181426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b541cdea-f3e2-4f63-895f-7d9af3ba6c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ds--text-field--input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>134fe290-554d-4ba3-b3aa-1c09e8a58cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-text</value>
      <webElementGuid>dc0b44ea-9651-4743-a707-ff3137626e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayText</value>
      <webElementGuid>b6c31a77-fb4b-43aa-90cf-c18fa0d9c114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text to display</value>
      <webElementGuid>83112b76-ea84-4a8d-a83e-813b41a26e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_19itidpf _11c82smr _12ji1r31 _1qu2glyw _12y31o36 _vchhusvi _1bsb1osq _1ul9idpf _bfhk1j28 _syaz1kw7 _80om1kw7 _14jiu2gc _olc6u2gc _1kod12x7 _7ba012x7 _1goxglyw _13xeglyw _1n7e1l2s _1idr131l</value>
      <webElementGuid>eb294328-ea71-4ca7-a8a7-6efdc80acaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://wwwyoutube.com</value>
      <webElementGuid>aa920256-28c4-42d8-8edf-aa1d6fdf807f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayText-uid81&quot;)</value>
      <webElementGuid>5d5cd211-2bec-412b-ac47-42393cf7c9f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayText-uid81']</value>
      <webElementGuid>7e46cd66-c78a-4a50-9c0a-75ad634f000f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>752e9ade-6a1e-4e0a-89d1-6e4737e84f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayText-uid81' and @name = 'displayText' and @placeholder = 'Text to display']</value>
      <webElementGuid>877b9f21-58a5-4419-8216-e9472bc71b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
