<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display text (optional)_displayText-uid82</name>
   <tag></tag>
   <elementGuidId>ffc5543c-315b-4966-b6fa-705061409b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayText-uid82</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayText-uid82']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b64d36ea-41bb-4054-ad5f-66bb94761a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined displayText-uid82-error</value>
      <webElementGuid>c2f88b82-b7e3-44b9-95ec-20c85a670492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>displayText-uid82-label</value>
      <webElementGuid>aaab0d4d-1a53-48ae-a2c3-d3d48cfa739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayText-uid82</value>
      <webElementGuid>de10c397-63cc-482f-b7cb-ed263187a300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e40c9893-40a0-447f-bd10-92e758d2c625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ds--text-field--input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c4a3b1a-369a-453e-98e2-c48980f162a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-text</value>
      <webElementGuid>c0c18750-6d49-41e1-828b-44417a170081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayText</value>
      <webElementGuid>bfe95700-b37d-4d87-9220-b5627b5ab487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text to display</value>
      <webElementGuid>27e28649-8569-4832-8d3a-2299df1dda2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_19itidpf _11c82smr _12ji1r31 _1qu2glyw _12y31o36 _vchhusvi _1bsb1osq _1ul9idpf _bfhk1j28 _syaz1kw7 _80om1kw7 _14jiu2gc _olc6u2gc _1kod12x7 _7ba012x7 _1goxglyw _13xeglyw _1n7e1l2s _1idr131l</value>
      <webElementGuid>86342432-2ccc-49e3-8b3f-6faf6c396f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Siêu thị nội thất &amp; trang trí Baya</value>
      <webElementGuid>75a16773-dbd5-4ccc-bba8-3be8c21c3446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayText-uid82&quot;)</value>
      <webElementGuid>47f2b405-5cb4-4130-b2ce-f78ebd06dc6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayText-uid82']</value>
      <webElementGuid>a215cbc6-3f6c-4eb7-8f44-47b1d547c72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0f143dcf-ff20-4e83-ab85-c368f0b39714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayText-uid82' and @name = 'displayText' and @placeholder = 'Text to display']</value>
      <webElementGuid>35921694-79ab-47cf-ac75-877e7de242bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
