<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search or paste a link_url-uid76</name>
   <tag></tag>
   <elementGuidId>86627fe9-4082-45bd-9e0c-678c7dd71ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#url-uid76</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='url-uid76']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78e7d14b-7ff3-4ea1-adf8-2ae4d2177124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>search-recent-links-field-description url-uid76-error</value>
      <webElementGuid>dd85b06e-6352-4640-8015-534e4afbc419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>url-uid76-label</value>
      <webElementGuid>be811886-93f5-4598-9403-03e0dfdf7ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>url-uid76</value>
      <webElementGuid>1bf9adb6-8a09-48e2-b627-ffb44b5be452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11538fef-36a7-4e9c-bfce-0344741fafee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6457c28-8632-4c5f-95bb-f2cf68e2371a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2964d573-0a44-431a-a21e-c9f462ff7633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6ae7afc-1a36-4ba0-9d81-8060cf14537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>3c22748f-3500-40b1-b798-95706382af60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>link-picker-search-list</value>
      <webElementGuid>5d955aaa-1940-4254-afd7-68d1d7e07e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ds--text-field--input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0090a578-6d3d-44f7-bf6b-f47172946564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>link-url</value>
      <webElementGuid>4d5767a3-f6d5-4e98-84cf-910fd00ab673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>f19c4a08-125b-43b9-8898-eb6c036e8029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Find recent links or paste a new link</value>
      <webElementGuid>193d62ed-d99c-4037-9835-78f837b16ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_19itidpf _11c82smr _12ji1r31 _1qu2glyw _12y31o36 _vchhusvi _1bsb1osq _1ul9idpf _bfhk1j28 _syaz1kw7 _80om1kw7 _14jiu2gc _olc6u2gc _1kod12x7 _7ba012x7 _1goxglyw _13xeglyw _1n7e1l2s _1idr131l</value>
      <webElementGuid>3c2222ab-6b85-41a4-a03f-3a8bb28b44c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;url-uid76&quot;)</value>
      <webElementGuid>83a30ae4-9d1f-4bd9-afa3-c1dd78422d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='url-uid76']</value>
      <webElementGuid>39061160-6838-42ee-b06e-8209aeff4e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>cc7fac0a-7df6-4a07-9a15-83f94240833f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'url-uid76' and @name = 'url' and @placeholder = 'Find recent links or paste a new link']</value>
      <webElementGuid>c77a8f36-c512-45f5-a34e-7dec71e14c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
