<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi_axfQxTmoD4JhYG_21</name>
   <tag></tag>
   <elementGuidId>b20f99f5-0e62-4308-b97a-c0f08af9c36c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.axfQxTmoD4JhYG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-back-title-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5a44f20f-333c-41a1-b45b-8765f19e5d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-back-title-input</value>
      <webElementGuid>4fa05cf4-212c-4cc0-a835-b136555b5d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>38686fa8-f08f-4d44-87e5-62d8d1e3a2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>axfQxTmoD4JhYG</value>
      <webElementGuid>c4072e2a-f1e7-4667-a379-2e147e9a0d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e2c83fd3-598a-42f5-8f13-21bf5ce03df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16384</value>
      <webElementGuid>148386e1-53bf-400b-a2e2-877087f184e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sửa tiêu đe·</value>
      <webElementGuid>45ebcde0-b968-4078-abf7-dcbc7cb54e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/div[@class=&quot;DGQMOEx8BBlPsz&quot;]/main[@class=&quot;OCBnVA6yk0XZsg z5cmpMyMY5EyBB&quot;]/section[@class=&quot;s7K43upMNnpWe4 qbwGmAROm5SJ2i sVvPkiJwx9PJsH&quot;]/hgroup[@class=&quot;hZBEE2fmsk8bYB Mwv8_O6L7qr8CP&quot;]/textarea[@class=&quot;axfQxTmoD4JhYG&quot;]</value>
      <webElementGuid>addf4eaf-6f36-4795-a340-adea5cba4e1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      <webElementGuid>168b9fec-5931-46db-94eb-4849f1053159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới'])[2]/following::textarea[1]</value>
      <webElementGuid>0df2db04-49c6-445c-af47-8c6589311a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[3]/following::textarea[1]</value>
      <webElementGuid>4b75816a-dbaf-4ffc-ad09-c484d358fe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::textarea[1]</value>
      <webElementGuid>e267426d-b5b6-43ab-bcad-fc47c0a31c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7eb256b7-aa55-4025-94f9-32720b2fe858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sửa tiêu đe·']/parent::*</value>
      <webElementGuid>2706cc44-d972-4f3c-8dfc-d52cf971068d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hgroup/textarea</value>
      <webElementGuid>d01f640c-bf67-4cb8-8536-c71f2106b061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sửa tiêu đe·' or . = 'Sửa tiêu đe·')]</value>
      <webElementGuid>ea029edc-5520-4e7d-bf2c-c8e3705da572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
