<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tc2</name>
   <tag></tag>
   <elementGuidId>30ad83f5-fe89-4e9f-83a0-75abe7d7719c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li/div/ol/li[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a49de6ba-9051-4e27-8594-db8ba7ad33d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LBbj8Ff4qXPj8l</value>
      <webElementGuid>cc6f4f8c-042a-4d76-a447-3be63241503a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tc2</value>
      <webElementGuid>06a67939-dfd4-4a32-9f91-d8e478ea1568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LBbj8Ff4qXPj8l&quot;]</value>
      <webElementGuid>f90e6060-c792-44fc-b594-db8919ea2044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li/div/ol/li[2]/div/div/div</value>
      <webElementGuid>93e17292-53c6-4f18-b3fb-b4144ac12f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tc1'])[1]/following::div[10]</value>
      <webElementGuid>1cb39417-1535-4b2b-a60a-370287dac282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cần làm'])[2]/following::div[21]</value>
      <webElementGuid>db617f2f-1d2f-42b4-b96d-70e42a00e940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tc3'])[1]/preceding::div[13]</value>
      <webElementGuid>e0ced71f-e4c4-4b17-8fe5-ff1df291dc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ol/li[2]/div/div/div</value>
      <webElementGuid>7f3de1db-a37e-416c-8241-309ae4f7e54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'tc2' or . = 'tc2')]</value>
      <webElementGuid>1510d060-4375-4924-a74d-d7af769eb642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
