<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_troubleshooting guide_QEGH0t6lsxm4C9</name>
   <tag></tag>
   <elementGuidId>4e095d71-6e3f-479a-99c8-42708767cad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/nav/header/div/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.QEGH0t6lsxm4C9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d64d1736-2bf6-455b-a2ea-cec48c4ab0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QEGH0t6lsxm4C9</value>
      <webElementGuid>354879d3-9e32-4293-a1b1-9057203e8444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Boards</value>
      <webElementGuid>e635878a-3495-4286-82b5-aab77a7a0e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/nav[@class=&quot;eOF7HLejybn5ad&quot;]/header[@class=&quot;qD23CmUpdDmVml&quot;]/div[1]/ul[1]/li[@class=&quot;WmhimhrsxjL1KU&quot;]/a[@class=&quot;wNdgQfwraPxaK7 _OR8kRsfIylR6J&quot;]/span[@class=&quot;QEGH0t6lsxm4C9&quot;]</value>
      <webElementGuid>1c74e2b1-69ff-4577-81e7-ecd982e0fc51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/nav/header/div/ul/li/a/span[2]</value>
      <webElementGuid>efb03dcb-b68f-4e2b-bc48-c534b12bb00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='troubleshooting guide'])[1]/following::span[17]</value>
      <webElementGuid>4483c003-bb1d-4c37-8e43-1557fd3abd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/preceding::span[4]</value>
      <webElementGuid>b5bd201b-752c-458b-aa0b-f55fb98c1008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[8]</value>
      <webElementGuid>60eda68a-9bd1-4c00-ba4e-956b069f65d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Boards']/parent::*</value>
      <webElementGuid>547c76c9-e689-4a38-bf7e-5f55412c59c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>8d7bd11c-c64a-4c39-872a-d297f9bc623a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Boards' or . = 'Boards')]</value>
      <webElementGuid>e6bc6a1e-4577-45d0-a6a5-923dd9ea51e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
