<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Recently viewed_GOPk_J9hMP7py5 (1)</name>
   <tag></tag>
   <elementGuidId>69efcb6f-7fd2-48c7-b4e4-cf6fd2cf84c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/main/div/div[2]/div/div[2]/div/a/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.GOPk_J9hMP7py5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>728e03a5-0e0d-4182-aa29-bcf129f24071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GOPk_J9hMP7py5</value>
      <webElementGuid>3c95686b-6447-4d76-9b06-11064089a55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo_1</value>
      <webElementGuid>f3b51df3-89bb-4e99-a2a4-0ecdcd1013cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/main[@class=&quot;WE1g1M6mHeG8Zv&quot;]/div[@class=&quot;N5JLl1bG1SMtDO&quot;]/div[2]/div[@class=&quot;_0WILnE2Yki1zE3&quot;]/div[@class=&quot;JeWt7esCgw4_73&quot;]/div[@class=&quot;Dm9SyZvpL8MyK1&quot;]/a[1]/div[@class=&quot;DixFsoZpaUkdLa&quot;]/div[@class=&quot;pIQ5_g4p0XJopD&quot;]/span[@class=&quot;GOPk_J9hMP7py5&quot;]</value>
      <webElementGuid>89a75f6c-911b-4c91-a1f4-7c1d4ab67645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/main/div/div[2]/div/div[2]/div/a/div/div[2]/span</value>
      <webElementGuid>08893d6a-f405-4b02-be96-cbe1c838a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently viewed'])[1]/following::span[1]</value>
      <webElementGuid>208ef42f-2a58-4660-920f-7690d743a873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân tích thiết kế hệ thống'])[1]/following::span[7]</value>
      <webElementGuid>b7ec01bd-0a01-4bee-8ecd-4bcf6e4fd087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;***'])[1]/preceding::span[4]</value>
      <webElementGuid>0d41cbc5-7ede-42ca-8014-1fde9b6d4b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang web tìm kiếm việc freelance'])[1]/preceding::span[6]</value>
      <webElementGuid>db2da83c-c679-47c1-93ef-cfb9d8e40ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo_1']/parent::*</value>
      <webElementGuid>61970f6b-3a62-4c54-8325-74c20cccb7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/span</value>
      <webElementGuid>a4030bc1-7bed-41f7-a6d4-b782cd880d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Demo_1' or . = 'Demo_1')]</value>
      <webElementGuid>99bdea15-eb29-4a7e-b4e5-aca286c4d82f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
