<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Workspace_Name</name>
   <tag></tag>
   <elementGuidId>2e0acfd4-08fa-4b2e-ad5b-58ad47a411d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'create-team-org-display-name')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1764233128446-create-team-org-display-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>497874cb-6e5b-4eab-bb5a-c21c61a38d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1764233128446-create-team-org-display-name</value>
      <webElementGuid>6e0c3940-8383-4437-9427-23176551668f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header-create-team-name-input</value>
      <webElementGuid>5db94991-240e-4474-80a0-db189f82daba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ed891b0-3ce0-46ac-b54d-09ac180daba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Efq_3CNn2MjJj1</value>
      <webElementGuid>4041b4fc-745c-453c-a5a7-33da090958b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e6f7618f-1b38-4712-8ed6-c558b87eb956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Taco's Co.</value>
      <webElementGuid>b6cc6969-63bb-4e08-8553-2c7206fda209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1764233128446-create-team-org-display-name&quot;)</value>
      <webElementGuid>e46b4113-d852-410e-89f2-f26fd5bb30d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1764233128446-create-team-org-display-name']</value>
      <webElementGuid>7abfc2ec-29ec-4aad-b55d-a92bde51ce8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-overlay']/div/div/div/div/div/form/input</value>
      <webElementGuid>5e00d4b6-5b15-4386-a2e8-11c9fc0cbefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>47219497-4241-4045-8792-212272bcf3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1764233128446-create-team-org-display-name' and @type = 'text' and @placeholder = concat(&quot;Taco&quot; , &quot;'&quot; , &quot;s Co.&quot;)]</value>
      <webElementGuid>9719c75d-3d34-4e97-9180-4b141e6400ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
