<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Name_card-copy-name_27</name>
   <tag></tag>
   <elementGuidId>051fcb30-8be4-44db-b2ef-7c0e5f6da666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-copy-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='card-copy-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-copy-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>38d64b62-ac76-42bf-ad85-faa02f4d79da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-copy-textarea</value>
      <webElementGuid>c649ac54-6ca5-4c1b-b44e-ca3515236e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-copy-name</value>
      <webElementGuid>6ed43657-a242-4bb3-8620-322f9b15b4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>7bbd57ac-f0c7-422b-b4b3-1c79be600940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>efa2fb7f-256f-4fb6-b8b0-9043a41676a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_zuMQT5LDymvSk</value>
      <webElementGuid>7b304fa0-1b95-4dfd-9e28-76ed7c2d9640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đây là thẻ thêm </value>
      <webElementGuid>f40d6b9f-27dc-4e79-9729-2acac7ab3421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-copy-name&quot;)</value>
      <webElementGuid>944a2c58-f907-43e4-99f5-272286228532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='card-copy-name']</value>
      <webElementGuid>53386fa4-115c-43e8-b363-33f98195925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>9f5f33b4-a5cc-43b6-a2b8-4aacbe290d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[2]/following::textarea[1]</value>
      <webElementGuid>f4f8eb71-a782-478d-a485-286d185e3001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy to…'])[1]/preceding::textarea[1]</value>
      <webElementGuid>40b3dabf-975a-44b7-9702-041b00f185ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[3]/preceding::textarea[1]</value>
      <webElementGuid>597849fc-b44d-4a56-8d88-5de614a0768d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đây là thẻ thêm']/parent::*</value>
      <webElementGuid>120dd9ae-2acc-4dc9-a84f-c0ef34d425aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>fdcc8c8c-d256-48b1-bf83-39d9d55e54ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Đây là thẻ thêm ' or . = 'Đây là thẻ thêm ')]</value>
      <webElementGuid>e8d97825-805c-4ee6-a881-41bd3acb79e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
