<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Name_card-copy-name_11</name>
   <tag></tag>
   <elementGuidId>26dacf46-0d68-4c08-a910-6b8961871c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-copy-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='card-copy-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-copy-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a9a422cf-d1b3-48f9-814d-1027fbc29a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-copy-textarea</value>
      <webElementGuid>56972605-d92c-4c5a-851f-96556351b56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-copy-name</value>
      <webElementGuid>c9ee9ccc-daa8-45fa-915a-fc871f2eb3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>9a5a07cd-7e7f-4d24-a3ba-a5a76a5203f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3ba37e14-5dca-40a0-9797-1634bac1f218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_zuMQT5LDymvSk</value>
      <webElementGuid>5c92be1c-574d-4057-8c76-8afb22868369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đây la</value>
      <webElementGuid>cd4ca58c-4d73-45b4-8d2c-ce57930a5867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-copy-name&quot;)</value>
      <webElementGuid>a1366284-4e6b-4de8-b3f6-c141d84640a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='card-copy-name']</value>
      <webElementGuid>c9fc2d88-6168-4227-a57e-9002293705a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>32cf757a-4458-4ed8-be17-f7d2b1cafd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[2]/following::textarea[1]</value>
      <webElementGuid>84115dfe-8d9a-4602-b5d1-2fc7f7f85ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy to…'])[1]/preceding::textarea[1]</value>
      <webElementGuid>53b7c44c-2302-4523-8341-3082eb9afbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[3]/preceding::textarea[1]</value>
      <webElementGuid>9fab88b8-7a17-457b-ad24-03c0fc6f1600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đây la']/parent::*</value>
      <webElementGuid>5cd29106-a6e5-418b-985b-b9c1e52b404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>b58fcbb1-1464-4f24-8b97-f89a08fee7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Đây la' or . = 'Đây la')]</value>
      <webElementGuid>899336b4-0d18-422e-b45f-5e80bdc4c80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đây la·']/parent::*</value>
      <webElementGuid>34b22b2a-a1c4-4624-8855-c2f4e011f170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Đây la·' or . = 'Đây la·')]</value>
      <webElementGuid>962acec4-94f5-4a00-b446-8c2f6d9101f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
