<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Name_card-copy-name_12</name>
   <tag></tag>
   <elementGuidId>51332f2b-a5e8-406e-91f9-7da752572b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-copy-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='card-copy-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-copy-textarea&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6a2f21fc-84fa-404b-b60e-10e5d968ddca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-copy-textarea</value>
      <webElementGuid>240cea63-23a3-48bd-a37b-374e9edd08df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-copy-name</value>
      <webElementGuid>217951f2-b9ce-48f5-b2a6-f4b30578f462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>abf16d3e-4cb1-4a7d-b89c-5d6064060f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>86c835db-c10e-4a0a-909b-5c72020c679a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_zuMQT5LDymvSk</value>
      <webElementGuid>ad187ee9-20ed-4e75-8f7b-031d88c05685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đây la·</value>
      <webElementGuid>f144fb7e-93dd-4901-ad3e-2f0736f1855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-copy-name&quot;)</value>
      <webElementGuid>3014f08a-008c-40f1-a129-3675e759aaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='card-copy-name']</value>
      <webElementGuid>56a7c290-64b9-45a7-91b6-f97a17a1963e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::textarea[1]</value>
      <webElementGuid>525287eb-be44-4655-b5f4-d6c26ea5de02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[2]/following::textarea[1]</value>
      <webElementGuid>1ce82f50-6949-4aa1-ab19-9bf5a9c3576d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy to…'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f26e67e6-110f-404e-bde4-cdb779338074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[3]/preceding::textarea[1]</value>
      <webElementGuid>36f383f0-d1d8-40c1-9633-c273bd46cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đây la·']/parent::*</value>
      <webElementGuid>415cb469-1baf-45db-8b61-7d30598fda6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/textarea</value>
      <webElementGuid>d0e053f0-fb3d-4efa-9021-123afa2c8c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Đây la·' or . = 'Đây la·')]</value>
      <webElementGuid>d2528d83-b590-4e72-89f2-011e9f09fef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đây là']/parent::*</value>
      <webElementGuid>78aa8884-33e0-4d85-843c-f58d1bbf909d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'card-copy-name' and @placeholder = 'Thêm thẻ mới' and (text() = 'Đây là' or . = 'Đây là')]</value>
      <webElementGuid>a202dc40-2ff8-47f2-b08d-d94d9f97ad4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
