<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi_axfQxTmoD4JhYG_15</name>
   <tag></tag>
   <elementGuidId>0ae1a162-bcb1-45e0-831b-f0d512302b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.axfQxTmoD4JhYG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-back-title-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>016ccc8b-cbfd-4d4e-9596-8d391e748c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-back-title-input</value>
      <webElementGuid>67dd1e22-b9fa-4413-ba96-b4f942b45f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>04e34766-24c2-4d42-a4a8-00341f715d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>axfQxTmoD4JhYG</value>
      <webElementGuid>1684026b-c337-45f3-abc8-5aaa56e2820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>70d9ecc6-41cf-476b-bdbf-b3400e9bf92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16384</value>
      <webElementGuid>248e8f9d-edc0-421b-8fbe-2f6ef2d0ba04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sửa tiêu</value>
      <webElementGuid>3e42ed49-928d-460f-85af-86469d3bdaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/div[@class=&quot;DGQMOEx8BBlPsz&quot;]/main[@class=&quot;OCBnVA6yk0XZsg z5cmpMyMY5EyBB&quot;]/section[@class=&quot;s7K43upMNnpWe4 qbwGmAROm5SJ2i sVvPkiJwx9PJsH&quot;]/hgroup[@class=&quot;hZBEE2fmsk8bYB Mwv8_O6L7qr8CP&quot;]/textarea[@class=&quot;axfQxTmoD4JhYG&quot;]</value>
      <webElementGuid>8cd56103-94eb-4b7b-ae0f-4dbd33703a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      <webElementGuid>a182db8e-4670-4654-b10f-ef61fc3ec9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới'])[2]/following::textarea[1]</value>
      <webElementGuid>671bc1c7-ea47-4a44-bdb5-184a69c2fc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[3]/following::textarea[1]</value>
      <webElementGuid>c0114476-6f7b-433c-8dbf-c5cdfab680c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::textarea[1]</value>
      <webElementGuid>1f2f3b8b-6df0-4983-9e72-8dce5f8ccd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d1cf9dc3-a3ae-4b5b-9bc1-dd3fc121d89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sửa tiêu']/parent::*</value>
      <webElementGuid>c59cae20-b2ee-454a-b6c4-49da80d004c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hgroup/textarea</value>
      <webElementGuid>47db51f2-8f8a-4b05-b06e-88266c7cc4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sửa tiêu' or . = 'Sửa tiêu')]</value>
      <webElementGuid>74f711b9-28ff-4ca1-b208-cfa8ff2ab36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
