<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi_axfQxTmoD4JhYG_23</name>
   <tag></tag>
   <elementGuidId>24406806-6a24-49d9-85cf-2f389d2a53a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.axfQxTmoD4JhYG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-back-title-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c49df8e2-db44-4c05-ad9e-aa269ef442e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-back-title-input</value>
      <webElementGuid>e42a5de3-609e-4227-9f26-e10f1ef0096d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Thêm thẻ mới</value>
      <webElementGuid>2bed9e77-eab2-4fea-b3ec-866f0329626d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>axfQxTmoD4JhYG</value>
      <webElementGuid>82a16e01-038c-4ed7-9a44-e281923834d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d1484fd8-0e46-4fdb-9ddc-49c9fd2115f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16384</value>
      <webElementGuid>1294b7a6-9956-43fc-a407-fbf7acdaec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sửa tiêu đê·</value>
      <webElementGuid>61dab183-50a9-43c1-92e4-d0fdf615d86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/div[@class=&quot;DGQMOEx8BBlPsz&quot;]/main[@class=&quot;OCBnVA6yk0XZsg z5cmpMyMY5EyBB&quot;]/section[@class=&quot;s7K43upMNnpWe4 qbwGmAROm5SJ2i sVvPkiJwx9PJsH&quot;]/hgroup[@class=&quot;hZBEE2fmsk8bYB Mwv8_O6L7qr8CP&quot;]/textarea[@class=&quot;axfQxTmoD4JhYG&quot;]</value>
      <webElementGuid>ae02fbfc-23fa-4c18-975f-afb373acbb3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      <webElementGuid>5f9976d0-07c6-468f-a423-fb1f729d43b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới'])[2]/following::textarea[1]</value>
      <webElementGuid>c8d949a8-ab25-4ca8-a271-463c37c33948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[3]/following::textarea[1]</value>
      <webElementGuid>f1896cb6-9ed4-4ded-bc91-a09f7b28ece5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::textarea[1]</value>
      <webElementGuid>3d34ba3b-99d7-4c37-ab28-2fdd80e8fe10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::textarea[1]</value>
      <webElementGuid>1e4ffb08-c8e3-4ab6-9a8d-3650849d2f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sửa tiêu đê·']/parent::*</value>
      <webElementGuid>68334dab-c94e-42c0-b005-e24f5b5c7c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hgroup/textarea</value>
      <webElementGuid>d6d81f99-e77c-4d80-ab0f-183b54942f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sửa tiêu đê·' or . = 'Sửa tiêu đê·')]</value>
      <webElementGuid>2152eeb8-dcb6-45f9-ba99-196e95e6b0cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
