<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start free trial_w68Pkbr8aRWmDF ybVB_99607a</name>
   <tag></tag>
   <elementGuidId>e0a495a1-8900-4940-89d4-d7785cdcc23e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-testid='create-board-submit-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.w68Pkbr8aRWmDF.ybVBgfOiuWZJtD.orotyyeYQx_tso._St8_YSRMkLv07</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db232d4e-3d03-4492-afa5-9bb02a51ba68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w68Pkbr8aRWmDF ybVBgfOiuWZJtD orotyyeYQx_tso _St8_YSRMkLv07</value>
      <webElementGuid>e44aadb3-7adf-4311-b316-b0b762443efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b98efc31-f8d5-4dd4-8c86-1bbb79d1ba35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>create-board-submit-button</value>
      <webElementGuid>b9d65bab-3a3b-4a46-ab4a-b96e4c106d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>b2abc887-cecd-4d05-a079-048b0c6c1d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;feplat3731&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM YzL7yRijWxDng8&quot;]/form[1]/button[@class=&quot;w68Pkbr8aRWmDF ybVBgfOiuWZJtD orotyyeYQx_tso _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>cbf8c483-dc34-4e22-8c01-0a908ab23671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@data-testid='create-board-submit-button']</value>
      <webElementGuid>ac3c715e-9c72-4e51-b99b-4c0646b1cad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>d0918ed1-56ca-49cd-b282-54a6692ced0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>32f0ad7f-df85-49de-b80f-682b3918f464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
