<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>2f48db67-a1d9-4ca3-aa2c-fe48abd82bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3-option-2']/li/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-option-2 > li.R4JCamcPDlrWzL > div.eQgJeMj8wdLrO7 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a977f00-dada-42cb-8864-dd83737820f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Public</value>
      <webElementGuid>fa42ccd1-6332-455c-9d3a-f4c970368f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-option-2&quot;)/li[@class=&quot;R4JCamcPDlrWzL&quot;]/div[@class=&quot;eQgJeMj8wdLrO7&quot;]/div[1]</value>
      <webElementGuid>d8f88778-3c51-4632-8db5-f05963e1100b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-option-2']/li/div[2]/div</value>
      <webElementGuid>989968b8-cd69-4b68-af8b-1de0a302eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All members of the 2025_Thu3_Ca3_Nhom5 Workspace can see and edit this board.'])[1]/following::div[6]</value>
      <webElementGuid>a6ef98f9-fedc-4754-b94b-c531b8796bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspace'])[3]/following::div[8]</value>
      <webElementGuid>b68566de-84b3-4111-9f7c-aae4708e7cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anyone on the internet can see this board. Only board members can edit.'])[1]/preceding::div[1]</value>
      <webElementGuid>584926a5-874e-4bfe-bb2b-54dd952d90ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Public']/parent::*</value>
      <webElementGuid>22c1c6d7-9a48-42ea-8a8d-bd7215de485e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/li/div[2]/div</value>
      <webElementGuid>99e6fd18-89a0-4d23-814b-7a4839f4420d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Public' or . = 'Public')]</value>
      <webElementGuid>cb4fc2d3-5466-417c-ab77-cc7a18d77033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
