<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_troubleshooting guide_jzNA5uVDhk7V5S</name>
   <tag></tag>
   <elementGuidId>a553cee1-6053-4540-a7d8-68861ebfad26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div[2]/div[2]/button/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.jzNA5uVDhk7V5S</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5e8280ae-6cd2-47c0-8cd6-d2ff497912c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jzNA5uVDhk7V5S</value>
      <webElementGuid>1cb58629-ea0c-457a-a3a0-6a3551c5860a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>27517246-3394-436b-a7be-4a465050db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;jYmd_yADRUL0GA&quot;]/div[@class=&quot;au4sy_aQekI5pl&quot;]/button[@class=&quot;kKCUvBL0NSbkMZ pQO2CwpZU2vLTS TsYBeI2Q3V9V09 PhzBALMp63PY_y eTemkd4Uuq3km8 ybVBgfOiuWZJtD orotyyeYQx_tso _St8_YSRMkLv07&quot;]/p[@class=&quot;jzNA5uVDhk7V5S&quot;]</value>
      <webElementGuid>1919acfa-0974-460b-9448-29c2706e6d98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div[2]/div[2]/button/p</value>
      <webElementGuid>0e4fcac8-ee7f-4926-851d-4ce452498b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='troubleshooting guide'])[1]/following::p[1]</value>
      <webElementGuid>b4151993-6cf3-4713-b959-2e8aef426933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boards'])[1]/preceding::p[1]</value>
      <webElementGuid>987f2f1b-280f-4e6b-856c-08873be048f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/preceding::p[1]</value>
      <webElementGuid>8f4eef19-7da8-44ad-be8f-18fde1622629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>36cc376d-2e60-4e54-b68a-51bd586e7eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>901bc202-89a7-4c41-83a8-e13f69b4453e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>4af9754d-c23a-46f9-ac2c-2ae9edf444ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
