<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_troubleshooting guide_QEGH0t6lsxm4C9 (1)</name>
   <tag></tag>
   <elementGuidId>7e416796-e22c-4151-80ca-1b1c84566eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/nav/header/div/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.QEGH0t6lsxm4C9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aecdc54a-d504-41a2-a5f7-09514ff1a161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QEGH0t6lsxm4C9</value>
      <webElementGuid>645b2394-57c3-4b7e-8ecd-aaed9d0ec719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Boards</value>
      <webElementGuid>5fb75fd7-0677-4c38-a73a-90d7a2b86132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/nav[@class=&quot;eOF7HLejybn5ad&quot;]/header[@class=&quot;qD23CmUpdDmVml&quot;]/div[1]/ul[1]/li[@class=&quot;WmhimhrsxjL1KU&quot;]/a[@class=&quot;wNdgQfwraPxaK7 _OR8kRsfIylR6J&quot;]/span[@class=&quot;QEGH0t6lsxm4C9&quot;]</value>
      <webElementGuid>b4f6ad12-5707-4e61-8990-5c0930fcd63a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/nav/header/div/ul/li/a/span[2]</value>
      <webElementGuid>e027f4b1-609b-46f2-9763-7eccc6be5295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='troubleshooting guide'])[1]/following::span[17]</value>
      <webElementGuid>10091424-5ee2-4490-8e39-660849a920a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/preceding::span[4]</value>
      <webElementGuid>8b556485-8625-4c92-91e2-88c83b1ab871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[8]</value>
      <webElementGuid>f876541c-e433-4966-83bb-8266844ddb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Boards']/parent::*</value>
      <webElementGuid>42609dd5-e04c-4efc-9e7a-c20767214b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>121fb594-1da3-4c7b-b57b-f865bed2f6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Boards' or . = 'Boards')]</value>
      <webElementGuid>0412ce6b-c7f9-48a7-a1d6-8aae648d2b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
