<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Recently viewed_GOPk_J9hMP7py5</name>
   <tag></tag>
   <elementGuidId>a1956b65-b61d-416f-aebb-9cd3467b6167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/main/div/div[2]/div/div[2]/div/a/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.GOPk_J9hMP7py5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d282439d-0e94-4c9c-8805-dc3274748cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GOPk_J9hMP7py5</value>
      <webElementGuid>8f2fff5c-fe69-4ee6-9786-f2aa579647ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo_1</value>
      <webElementGuid>0110e687-f6eb-448a-bb1e-c004ba643fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/main[@class=&quot;WE1g1M6mHeG8Zv&quot;]/div[@class=&quot;N5JLl1bG1SMtDO&quot;]/div[2]/div[@class=&quot;_0WILnE2Yki1zE3&quot;]/div[@class=&quot;JeWt7esCgw4_73&quot;]/div[@class=&quot;Dm9SyZvpL8MyK1&quot;]/a[1]/div[@class=&quot;DixFsoZpaUkdLa&quot;]/div[@class=&quot;pIQ5_g4p0XJopD&quot;]/span[@class=&quot;GOPk_J9hMP7py5&quot;]</value>
      <webElementGuid>f4c0c9ca-3519-4afb-824c-cd7c4395d2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/main/div/div[2]/div/div[2]/div/a/div/div[2]/span</value>
      <webElementGuid>1f525971-1918-42e0-aae2-d466f28a1680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently viewed'])[1]/following::span[1]</value>
      <webElementGuid>fc4dfb1e-4076-4043-9903-9b06cd716c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân tích thiết kế hệ thống'])[1]/following::span[7]</value>
      <webElementGuid>3a839cb6-8c3a-41d9-9dee-6c174551fac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo_1'])[2]/preceding::span[2]</value>
      <webElementGuid>f406abd2-db3e-41bf-9e4b-bac56ae73244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;***'])[1]/preceding::span[6]</value>
      <webElementGuid>191a3f70-4649-438f-bf94-f74ef4073f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo_1']/parent::*</value>
      <webElementGuid>a33ec132-8af3-4952-af35-7bda623cafb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/span</value>
      <webElementGuid>e589ff5b-72dd-467c-9b26-56f109a17a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Demo_1' or . = 'Demo_1')]</value>
      <webElementGuid>897f1ec6-5a30-421d-84a6-6213eb7cba90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
