<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Thm th mi aa_axfQxTmoD4JhYG_1</name>
   <tag></tag>
   <elementGuidId>2354f4f6-9d5d-4eeb-8e4f-4e79cfdf1367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.axfQxTmoD4JhYG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;card-back-title-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1051663d-484f-4611-b256-80e7d4a43c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-back-title-input</value>
      <webElementGuid>76e963fa-2669-4314-ae50-c3319f0e70ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Thêm thẻ mới aa</value>
      <webElementGuid>2a4bf251-84d9-428f-b3bd-aeb99fed0bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>axfQxTmoD4JhYG</value>
      <webElementGuid>bb7ee1e6-3df1-44fa-ab0f-1f357b04a760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>97d69f36-46aa-49e4-9877-37f3fed2232b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16384</value>
      <webElementGuid>1bb98ce0-5895-4bfb-a2ad-bec830c602e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm thẻ mới aass</value>
      <webElementGuid>741f61e6-aa37-410a-bac8-4253e34862bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/div[@class=&quot;DGQMOEx8BBlPsz&quot;]/main[@class=&quot;OCBnVA6yk0XZsg z5cmpMyMY5EyBB&quot;]/section[@class=&quot;s7K43upMNnpWe4 qbwGmAROm5SJ2i sVvPkiJwx9PJsH&quot;]/hgroup[@class=&quot;hZBEE2fmsk8bYB Mwv8_O6L7qr8CP&quot;]/textarea[@class=&quot;axfQxTmoD4JhYG&quot;]</value>
      <webElementGuid>c1e8cc7d-2742-4354-8006-320de20f4713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/section/hgroup/textarea</value>
      <webElementGuid>d8c74073-3433-4070-843d-ffd28ac210e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thẻ mới aa'])[2]/following::textarea[1]</value>
      <webElementGuid>4dafd55b-1ddb-404b-a0fc-e0a17c13a34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm thử trello'])[3]/following::textarea[1]</value>
      <webElementGuid>483d9cc6-515f-472d-ae0f-89d41c6eb166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::textarea[1]</value>
      <webElementGuid>afefd93b-1ae5-48cf-aec7-c9aab1a311ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::textarea[1]</value>
      <webElementGuid>806477b9-31ac-4d6f-b395-48bfeec41553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm thẻ mới aass']/parent::*</value>
      <webElementGuid>04908d86-aad4-40a6-8227-cc1c4c3ee56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//hgroup/textarea</value>
      <webElementGuid>a9caaa99-4b46-4651-8585-34f572ba4e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Thêm thẻ mới aass' or . = 'Thêm thẻ mới aass')]</value>
      <webElementGuid>0abd07b0-269a-44bc-aadf-2c25d659a3c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
