<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ang lm_Ns0Sj0nEGMQ7un</name>
   <tag></tag>
   <elementGuidId>2536e287-4407-49f4-a482-5cdab0bc8a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7046806-3b6b-4658-9781-208992d74b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bbe5c406-b6b0-43fd-a3ba-e8ecc7cfc8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ns0Sj0nEGMQ7un</value>
      <webElementGuid>4295476f-2779-4785-82c5-b5094b3dd26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>726167ae-bd4a-4a82-a65f-9e2d794b624a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/1ff2PwH1/5-xong-30-video-anh-trong-tu%E1%BA%A7n-n%C3%A0y-2342025-2742025</value>
      <webElementGuid>8f454ed4-641c-48f4-b5ec-3f19feca022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-name</value>
      <webElementGuid>9bd8b615-14f0-416b-8bfb-8b1edf0450b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xong 30 video anh trong tuần này (23.4.2025 - 27.4.2025)</value>
      <webElementGuid>9ee09192-39be-442a-ae45-b66054697faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LBbj8Ff4qXPj8l&quot;]/div[@class=&quot;NYIHAreWw6Ga8y kCaocI3DJaoQ38&quot;]/span[@class=&quot;WpBdHiAP8hTeQK OZOw_0q9XfR1sR&quot;]/a[@class=&quot;Ns0Sj0nEGMQ7un&quot;]</value>
      <webElementGuid>8516453f-e273-4971-a1b0-3849dda746c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      <webElementGuid>4deab12e-2d82-40e7-a881-5d941a506cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xong 30 video anh trong tuần này (23.4.2025 - 27.4.2025)')]</value>
      <webElementGuid>c74a4d50-7d67-47ba-ae8f-614e4bcc2391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang làm'])[2]/following::a[1]</value>
      <webElementGuid>1a024fc5-6125-4b3b-92bb-9629e484cfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang làm'])[1]/following::a[1]</value>
      <webElementGuid>4a9d4327-25fd-45ac-9b5b-0b8dd22569e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày 24/04 Cày tới bài 30'])[1]/preceding::a[1]</value>
      <webElementGuid>7316dab6-1c97-47e7-8565-b27035b37932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a card'])[2]/preceding::a[2]</value>
      <webElementGuid>ed6449b2-8f30-45bd-a9fa-65a325332a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xong 30 video anh trong tuần này (23.4.2025 - 27.4.2025)']/parent::*</value>
      <webElementGuid>2c218c32-3438-459c-ab25-55c367d790a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/1ff2PwH1/5-xong-30-video-anh-trong-tu%E1%BA%A7n-n%C3%A0y-2342025-2742025')]</value>
      <webElementGuid>c95d8750-ae0a-4a6d-87b2-ee17e06bb6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      <webElementGuid>371f88b7-3872-447f-b4c0-72189aa9f79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/1ff2PwH1/5-xong-30-video-anh-trong-tu%E1%BA%A7n-n%C3%A0y-2342025-2742025' and (text() = 'Xong 30 video anh trong tuần này (23.4.2025 - 27.4.2025)' or . = 'Xong 30 video anh trong tuần này (23.4.2025 - 27.4.2025)')]</value>
      <webElementGuid>f23e7cfb-9a57-4a06-8568-60008361f9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
