<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keep all Power-Up data_ybVBgfOiuWZJt_21783f</name>
   <tag></tag>
   <elementGuidId>a7552638-16aa-418e-aaaf-34d73d7dcf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ybVBgfOiuWZJtD.Bs17adKBbSQrdA.Y8VSmRstKSzhJH._St8_YSRMkLv07</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[32]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>598ab754-32df-439c-8622-6fdfa0ba220d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ybVBgfOiuWZJtD Bs17adKBbSQrdA Y8VSmRstKSzhJH _St8_YSRMkLv07</value>
      <webElementGuid>0234eaba-4120-4cd6-8bcc-8592c1f725a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8b5749d-ebec-44a2-804f-f530e2680a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>disable-powerup-button</value>
      <webElementGuid>958b5f51-9834-4d5d-9ce7-36676f537a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disable Power-Up</value>
      <webElementGuid>a0495270-5e45-41f0-81e9-fbed91f1ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[2]/div[1]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/button[@class=&quot;ybVBgfOiuWZJtD Bs17adKBbSQrdA Y8VSmRstKSzhJH _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>6626a1d0-cda6-47f8-a78c-c49b8f91f5d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[32]</value>
      <webElementGuid>a993a6c1-1ac4-40c6-a6dc-cfede68da1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/button</value>
      <webElementGuid>968a59c5-bb02-4126-9e71-d53d4bc2a6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep all Power-Up data'])[1]/following::button[1]</value>
      <webElementGuid>0c366e79-a1be-453e-92a2-1a2bb2ed5abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>397ec378-a6ea-4fde-ac7e-afc1a2c11e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disable Power-Up']/parent::*</value>
      <webElementGuid>b2dc099f-4edd-4190-a18c-d2e01cb9906f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>8991840f-1420-4215-961b-a482c48c4b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Disable Power-Up' or . = 'Disable Power-Up')]</value>
      <webElementGuid>fa354058-60e6-4d45-9f44-8393f9fddaf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
