<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Who is allowed to vote on cards_LOhI_fbf2ac</name>
   <tag></tag>
   <elementGuidId>f2445fc9-dff5-4d4b-90d2-c7dedbb961b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.LOhIKSjx1ImXEH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4720ab60-28d8-473c-823f-991ff2f4190c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LOhIKSjx1ImXEH</value>
      <webElementGuid>3f027153-131d-4c0c-a581-b5518c7dcdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MembersAdmins and board members can vote.</value>
      <webElementGuid>8749c9b1-57a3-428f-a26f-84909918772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[2]/div[1]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[@class=&quot;js-react-root&quot;]/div[1]/div[@class=&quot;UZFgTnUqKFdI6u&quot;]/ul[1]/li[1]/button[@class=&quot;LOhIKSjx1ImXEH&quot;]</value>
      <webElementGuid>ea48c8ad-80ca-4b0a-bce0-b4a76de03c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li/button</value>
      <webElementGuid>fff1760f-fc8a-444f-ad4f-58bd7c209ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who is allowed to vote on cards?'])[1]/following::button[1]</value>
      <webElementGuid>92f1d4f6-65ee-47ff-8ffd-ec3bbc854df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voting settings'])[1]/following::button[1]</value>
      <webElementGuid>d26149e7-5fd6-41dd-bedb-e039635bd459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>11f72b73-b5fd-4706-bb3e-9d2eabf2f987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'MembersAdmins and board members can vote.' or . = 'MembersAdmins and board members can vote.')]</value>
      <webElementGuid>da0bee96-fc2e-45d8-80ff-4a7dc896b22a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
