<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Trao quyn cho mi ngi v cho php ngi d_65442d</name>
   <tag></tag>
   <elementGuidId>b178d33d-4946-4440-bc25-90777ec0e78f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[67]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bda79375-9abd-425d-b2e6-b0511f36513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ybVBgfOiuWZJtD _St8_YSRMkLv07</value>
      <webElementGuid>3f4c745d-39ef-4a2b-b6a5-28627bc2716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0926264a-48a1-4470-b286-8862c63e79e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>pup-settings-button</value>
      <webElementGuid>22c17f4d-b18f-4387-8d5e-321c778f5ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>cd90a45b-5fd0-439d-9ab2-5381fab3930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;feplat3731&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw xVpVGkNsehZDGL js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM BxnW01nt1ospt1 YzL7yRijWxDng8 uS2wuOb6bRMSqo&quot;]/div[@class=&quot;u-fancy-scrollbar doMDJc2FHLfUXa&quot;]/div[@class=&quot;AuS13buKHrY4Zn&quot;]/div[@class=&quot;yGvABqiVKdLlz2&quot;]/button[@class=&quot;ybVBgfOiuWZJtD _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>7064e4c1-36dd-4d19-97ea-f2077b7265ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[67]</value>
      <webElementGuid>55906068-b5f7-42c7-9c7f-b3bc70cfff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trao quyền cho mọi người và cho phép người dùng bỏ phiếu trên các thẻ.'])[1]/following::button[1]</value>
      <webElementGuid>3ba25001-b996-49f4-a3d3-15e7547c2c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bình chọn'])[1]/following::button[1]</value>
      <webElementGuid>4666e5de-64d3-493d-a528-eb22e434a928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Box'])[1]/preceding::button[1]</value>
      <webElementGuid>8d50d8f8-3c30-491f-8a90-4ec245cec81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem thông tin cập nhật và xem trước cho các tệp hoặc thư mục Box được đính kèm vào thẻ.'])[1]/preceding::button[1]</value>
      <webElementGuid>d2c0978a-5fe5-4e7b-a461-c24d0c89a9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/button</value>
      <webElementGuid>2f2ddaa5-b25f-4138-99f0-fadf2e4d1590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>862c5f97-d7e8-4400-851b-b8c09a0547d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
