<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Who is allowed to vote on cards_bH80Rv_ec0b65</name>
   <tag></tag>
   <elementGuidId>bf1e5f35-61f0-453e-8d1d-5b562037cb0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bH80RvHHmoWYhk.wz7UJENPuf2pDX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cb16bf7-0129-4fab-9b94-c916351310f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bH80RvHHmoWYhk wz7UJENPuf2pDX</value>
      <webElementGuid>4f3444e2-544f-40b6-8cb3-9eb66dce53d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>e721d808-0f8d-45b2-99cf-ee745f6bf9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[2]/div[1]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[@class=&quot;js-react-root&quot;]/div[1]/div[@class=&quot;UZFgTnUqKFdI6u&quot;]/ul[1]/li[1]/button[@class=&quot;LOhIKSjx1ImXEH&quot;]/span[@class=&quot;bH80RvHHmoWYhk wz7UJENPuf2pDX&quot;]</value>
      <webElementGuid>6b4b4a31-5968-4c1a-965d-79f2a025f4bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div[2]/div/div[2]/div/div/div/ul/li/button/span</value>
      <webElementGuid>6a993b83-7abc-4810-8534-02561daccc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who is allowed to vote on cards?'])[1]/following::span[1]</value>
      <webElementGuid>3f938660-bd07-4be6-935f-aaacf3f65b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voting settings'])[1]/following::span[1]</value>
      <webElementGuid>689ec655-88f1-483c-991e-e66ee5afa847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admins and board members can vote.'])[1]/preceding::span[2]</value>
      <webElementGuid>8e380e17-5198-4a8c-84ea-68215a5ff1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button/span</value>
      <webElementGuid>aa8f8890-e0ec-49bd-b2bf-93052ed8e3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Members' or . = 'Members')]</value>
      <webElementGuid>0d73abd4-04b0-4e9b-beeb-a1badd19a6fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
