<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A_QEGH0t6lsxm4C9</name>
   <tag></tag>
   <elementGuidId>c5637782-e52c-4e7f-bf40-65962820f17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.IyWeSHzb5z4TTx > ul > li.WmhimhrsxjL1KU > a.wNdgQfwraPxaK7 > span.QEGH0t6lsxm4C9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/nav/section/div/section/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>777395f1-621f-495b-8eef-fcf6fff732d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>home-team-tab-name</value>
      <webElementGuid>594ecaef-c92b-49be-bdd5-8c4a38b6ce63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QEGH0t6lsxm4C9</value>
      <webElementGuid>476a095b-e9a8-4d35-9f10-ca10022db4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>abcs</value>
      <webElementGuid>0047a947-d48f-4784-b6b4-8ff64e45e3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;igs0P2yeiJmpkk&quot;]/div[@class=&quot;witf2lW81DY7WP&quot;]/nav[@class=&quot;eOF7HLejybn5ad&quot;]/section[@class=&quot;v2yaj6y7dtFy4C&quot;]/div[1]/section[@class=&quot;IyWeSHzb5z4TTx&quot;]/ul[1]/li[@class=&quot;WmhimhrsxjL1KU&quot;]/a[@class=&quot;wNdgQfwraPxaK7&quot;]/span[@class=&quot;QEGH0t6lsxm4C9&quot;]</value>
      <webElementGuid>7ce9cf14-1249-4281-8af6-625d44a34383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/nav/section/div/section/ul/li/a/span</value>
      <webElementGuid>56c94e36-a3e2-491f-ba32-411d2f018cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::span[1]</value>
      <webElementGuid>a878d7be-cdd2-4710-982b-ae7e33633890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspaces'])[1]/following::span[1]</value>
      <webElementGuid>1ec8010b-9b79-46c7-bc60-e02cd3be3ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[2]/preceding::span[4]</value>
      <webElementGuid>93060c45-bf34-4669-b084-0c1e9d59087e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ahs'])[1]/preceding::span[4]</value>
      <webElementGuid>9ad5929c-c29d-403f-9424-69c5d335516e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='abcs']/parent::*</value>
      <webElementGuid>e556908a-104c-457c-870a-5b5de114bc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/a/span</value>
      <webElementGuid>f22a51ef-9e3d-4a25-b2be-0fdab829c58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'abcs' or . = 'abcs')]</value>
      <webElementGuid>aa89039a-0fb3-4635-b64e-1fafe9b482e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
