<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_textfield_filter</name>
   <tag></tag>
   <elementGuidId>90567a80-13c7-41bf-895d-4fe42bbb6ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.nch-textfield__input.a3omnNx_j558kc.a3omnNx_j558kc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter a keyword…']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb634ace-c3b2-4400-8788-6a0c4521cd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-textfield__input a3omnNx_j558kc a3omnNx_j558kc</value>
      <webElementGuid>734d32ba-2d35-4a69-8372-ca75bcfe903a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1cd2fe3-24de-4257-833b-a44c139ce4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a keyword…</value>
      <webElementGuid>1cdf2e19-fc80-4c22-acf0-38c90477d38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Enter a keyword…</value>
      <webElementGuid>10ec7c7d-e7da-40f3-8f67-09fdd90281c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>d75cb402-dce1-48fb-989a-64492dcc6d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mdl-js&quot;]/body[@class=&quot;feplat3731&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM YzL7yRijWxDng8&quot;]/div[1]/input[@class=&quot;nch-textfield__input a3omnNx_j558kc a3omnNx_j558kc&quot;]</value>
      <webElementGuid>a31c383a-78c8-4c57-a3cb-262154edf1bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P']</value>
      <webElementGuid>550dd326-9b31-453f-a28f-f74f9cce1dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>139eb8f4-a368-4161-80ad-c1cd94559ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter a keyword…']</value>
      <webElementGuid>1545ee50-b3f5-4a9b-a910-381e61117f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
