<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>648f4733-ce34-45f9-87f5-f792a3f02c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li[3]/div[2]/div/div/div/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c8c8a03d-0d8b-4178-b7f7-0887e2b1de1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-renderer-start-pos</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0cffcf14-b4e6-4dea-b526-8cc06ead49e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t3</value>
      <webElementGuid>42b5a534-4f4a-4cd6-b332-25b61527b277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/div[@class=&quot;DGQMOEx8BBlPsz&quot;]/main[@class=&quot;OCBnVA6yk0XZsg z5cmpMyMY5EyBB&quot;]/div[@class=&quot;hzcmJzuca9EAAu&quot;]/div[@class=&quot;jPU40MEIQllLnJ&quot;]/section[@class=&quot;s7K43upMNnpWe4&quot;]/div[@class=&quot;N_3ir40qWUR8gh PIClXRhqsb9NWy&quot;]/ul[@class=&quot;b15uaOHxe6_H9b&quot;]/li[@class=&quot;Loo6cCxtB5Us48&quot;]/div[@class=&quot;hZtdCwUKPA9Wlx&quot;]/div[@class=&quot;GDNiqcuCRnnaGy&quot;]/div[1]/div[@class=&quot;uilHrMFcZTKnuh GyLFmHlBcEbabD&quot;]/div[@class=&quot;ak-renderer-wrapper is-full-width css-1jke4yk&quot;]/div[@class=&quot;css-p38xzc&quot;]/div[@class=&quot;ak-renderer-document&quot;]/p[1]</value>
      <webElementGuid>cb85c6b1-125f-401f-964c-2b353481357e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li[3]/div[2]/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>26ffe422-8ea9-4561-bd99-e49c4b3ec82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::p[3]</value>
      <webElementGuid>619e860a-5f43-4b1f-afa1-7036bc65b56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::p[3]</value>
      <webElementGuid>d8723eb3-0e50-4376-9c15-9c64504fb9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[3]/preceding::p[1]</value>
      <webElementGuid>8a859c72-0cbd-462e-9b32-7eb468cde5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::p[1]</value>
      <webElementGuid>59bd3f8c-b98c-42d5-8191-25fd9fdc9a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t3']/parent::*</value>
      <webElementGuid>1889372d-38fa-48b2-b834-e54586384b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>656c986b-86b1-48ea-b723-2052e81d1747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 't3' or . = 't3')]</value>
      <webElementGuid>b98a2c18-a156-4a9c-a2e9-a473259e74cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
