<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_edit-checkitem-693127dc8d0c_11b3a0_15</name>
   <tag></tag>
   <elementGuidId>dadd4e0e-1349-4cdd-aaf2-099d34bd284d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-checkitem-693127dc8d0c95d7420d2a2f' and (text() = 'tai123' or . = 'tai123')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>66cc8969-823d-4115-ab35-60b1a743186b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>bb681912-b1ae-4a88-87ea-c0296d4fdf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d38kp4igs6lfMM</value>
      <webElementGuid>38e07b21-5866-4b63-9e15-c4419c5d73e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      <webElementGuid>c243f67e-3c2a-4f01-b4c1-b4f2150eec1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tai123</value>
      <webElementGuid>9d906971-ab10-4654-9cbc-3b7620528725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-checkitem-693127dc8d0c95d7420d2a2f&quot;)</value>
      <webElementGuid>f631f690-17d1-4f26-bead-fbe82027cf1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      <webElementGuid>5e82b882-4340-49a5-aa6a-55b47c3d9dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li/div[2]/form/textarea</value>
      <webElementGuid>37b01679-3cc4-42a8-add2-e250151d7da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::textarea[1]</value>
      <webElementGuid>66e1dcd4-e83d-45a3-a3d0-0da3ba7ac4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::textarea[1]</value>
      <webElementGuid>18e9f4e3-ca00-4ae8-95d0-d7568981206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::textarea[1]</value>
      <webElementGuid>26f76132-980d-4546-bcd3-03ba89e73ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0e4adba9-1d13-4c38-9958-0a4741d64fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tai123']/parent::*</value>
      <webElementGuid>5befd752-1c1a-44f0-8f03-5cdfd40d5ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>d46454d1-22de-452a-a9c5-26802dce4360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-checkitem-693127dc8d0c95d7420d2a2f' and (text() = 'tai123' or . = 'tai123')]</value>
      <webElementGuid>7c3e017a-242a-4401-a12d-20e47bc84b5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
