<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_edit-checkitem-693127dc8d0c_11b3a0_1</name>
   <tag></tag>
   <elementGuidId>2ce6bdac-dd07-4b3b-83f5-51aa119442a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ff202285-5071-4250-b762-1f738ac93245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4c05766c-e1d2-46bb-823b-4b0e57a57006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d38kp4igs6lfMM</value>
      <webElementGuid>b96e2ba4-7ae1-456c-a3c2-a9fa1a6e1edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      <webElementGuid>f43aed46-3c57-4f97-ac4a-635acbb14492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>google.c</value>
      <webElementGuid>6e4bd821-d9ce-4c22-b05b-18ab0e63c0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-checkitem-693127dc8d0c95d7420d2a2f&quot;)</value>
      <webElementGuid>4c0012ed-ab5e-4c3e-bd67-13982ef02d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      <webElementGuid>6c5b2c5f-e645-4fd7-a647-01bfc21dd7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li/div[2]/form/textarea</value>
      <webElementGuid>c2b7e6ad-b18d-4aed-8cfa-8ad63ccb7578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::textarea[1]</value>
      <webElementGuid>5546a221-becf-4b46-9b93-6293b230b321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::textarea[1]</value>
      <webElementGuid>60cd8521-a5e1-449e-b6e5-3673c4b4b5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d506368d-f07d-4aed-affd-06b5d6f15836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b64dd0db-6c05-4b3e-80a4-85c62100cc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='google.c']/parent::*</value>
      <webElementGuid>5dcf065e-7a14-4238-a257-37d14e15a179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>778fa42e-20db-4316-8526-045b031f5028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-checkitem-693127dc8d0c95d7420d2a2f' and (text() = 'google.c' or . = 'google.c')]</value>
      <webElementGuid>e035cf14-9aec-48b6-9a07-1720f33057a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
