<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_edit-checkitem-693127dc8d0c_11b3a0_6</name>
   <tag></tag>
   <elementGuidId>3cf8fe43-8fab-4b4a-bcad-780a7e23050c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dd18bfa3-89d0-44ea-858b-89fa03a34e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>89fca7e9-2338-4099-bac7-9a254e92f8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d38kp4igs6lfMM</value>
      <webElementGuid>90bd7ed9-6074-4e46-b39e-79c64a70004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      <webElementGuid>69c02e2f-8b83-4723-a5bb-ca8abc09c8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>goo</value>
      <webElementGuid>f5aee7c7-5246-4bec-a69e-382077c22868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-checkitem-693127dc8d0c95d7420d2a2f&quot;)</value>
      <webElementGuid>82a4fa83-ed02-44e6-ab46-24aa9f868b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      <webElementGuid>48e587f9-edc5-4813-a795-780c16a13fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li/div[2]/form/textarea</value>
      <webElementGuid>5ebdf84a-a666-4ee1-9df5-35f72edbd9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::textarea[1]</value>
      <webElementGuid>8c27b643-61b5-479f-a6f6-bd88ec265ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::textarea[1]</value>
      <webElementGuid>1434422f-22b6-4705-99f4-e72de3c254d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::textarea[1]</value>
      <webElementGuid>85fd7734-7b1b-4b11-9997-528fedaca6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e07ac83d-04de-41e9-af06-6631bb432bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='goo']/parent::*</value>
      <webElementGuid>ef61b0dd-8678-4543-9d48-a1290b57badb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>0f5f5d96-59b8-4b17-a267-b85fb52ded6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-checkitem-693127dc8d0c95d7420d2a2f' and (text() = 'goo' or . = 'goo')]</value>
      <webElementGuid>a014ed8b-bebf-4539-93ff-4e7fbc3b9f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
