<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_add-checkitem-6931020b84e85_d5f0b6_1</name>
   <tag></tag>
   <elementGuidId>fe775eaa-27ba-4f64-b5f8-b45afa9b584c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='add-checkitem-6931020b84e8518e12c80ed0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-checkitem-6931020b84e8518e12c80ed0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>88ac97e2-19a1-4e29-b30a-db9b32d4b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>check-item-name-input</value>
      <webElementGuid>3d707ee2-c3b2-4413-9aa1-ddcded9b4e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add an item</value>
      <webElementGuid>60b4109c-2304-4b4e-ae8f-82aa4d398c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3e91957d-d174-4704-bc06-5bc7d3ff41ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CfQ1Gu9vrIMPLB</value>
      <webElementGuid>5f2ff77f-6810-4565-834e-91c743b22e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add an item</value>
      <webElementGuid>678e442a-3be4-4f02-a2b6-3c42b28d030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-checkitem-6931020b84e8518e12c80ed0</value>
      <webElementGuid>5392fad9-7c4a-48c8-8993-bf852514790c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t5</value>
      <webElementGuid>ced82ee9-d45c-4cef-b243-17b7760ead48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-checkitem-6931020b84e8518e12c80ed0&quot;)</value>
      <webElementGuid>8bd8299a-228d-42ee-bc7b-a30d55dbb3c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='add-checkitem-6931020b84e8518e12c80ed0']</value>
      <webElementGuid>c7f5839b-bbe7-4675-9b6b-3da6d997da47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/div[2]/form/textarea</value>
      <webElementGuid>0f2e7a88-a0c4-4405-8b7b-8386f601576a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::textarea[1]</value>
      <webElementGuid>a2c31a52-4961-4e1d-b597-f6a52fc22558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::textarea[1]</value>
      <webElementGuid>a49598c4-4bb8-44a3-a817-315690b5853f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[3]/preceding::textarea[1]</value>
      <webElementGuid>3cd310c8-104d-4a12-9c08-a33e13a4e807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3b0364a6-45c4-440d-94e5-e313372d582a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t5']/parent::*</value>
      <webElementGuid>14fb7ae8-5d89-4d57-980e-926cdf7d66a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>9a8c49f1-8629-43a9-9d0c-7e720cd3279a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add an item' and @id = 'add-checkitem-6931020b84e8518e12c80ed0' and (text() = 't5' or . = 't5')]</value>
      <webElementGuid>50d2e597-7cfb-47d4-8ae7-ea0a6cb177d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t4']/parent::*</value>
      <webElementGuid>3a84c017-bb1b-4b01-90f6-9d9f24a7035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add an item' and @id = 'add-checkitem-6931020b84e8518e12c80ed0' and (text() = 't4' or . = 't4')]</value>
      <webElementGuid>3f83c9d5-1df5-414e-b831-e3d57a85b0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t3']/parent::*</value>
      <webElementGuid>062d6a9c-8372-4356-adb1-e470350b3394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Add an item' and @id = 'add-checkitem-6931020b84e8518e12c80ed0' and (text() = 't3' or . = 't3')]</value>
      <webElementGuid>4fc13216-a87b-41a3-8b59-5ff9e8779b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
