<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Delete_edit-checkitem-693127dc8d0c_11b3a0_10</name>
   <tag></tag>
   <elementGuidId>85424387-8695-45a0-b26b-8f6406332346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>523c2f2d-97f2-414c-a7d6-5c3eb8edf573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b5560dda-04c0-4154-a0ab-274e52eabf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d38kp4igs6lfMM</value>
      <webElementGuid>ae5e3fab-4853-42fa-ad28-694c4f6ac185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-checkitem-693127dc8d0c95d7420d2a2f</value>
      <webElementGuid>5a055637-055a-41fe-a2fb-6640f650ed8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>21270641-3e32-466d-917c-034150a1f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-checkitem-693127dc8d0c95d7420d2a2f&quot;)</value>
      <webElementGuid>c61cc079-42c0-4a60-912b-12bcae90f206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit-checkitem-693127dc8d0c95d7420d2a2f']</value>
      <webElementGuid>bb11fa96-1fb5-4403-bc27-10da5c1a7b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/div[2]/section/div[2]/ul/li/div[2]/form/textarea</value>
      <webElementGuid>d8bbe57e-86df-4d4a-b86e-38bbbf77e9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::textarea[1]</value>
      <webElementGuid>1e528ccc-8897-4edc-8278-a89865217fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc cần làm'])[1]/following::textarea[1]</value>
      <webElementGuid>622b903f-5b16-4cb5-8d28-a4d078378fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a9a09981-f361-4315-b45e-ac39bd92bfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7818ad7b-9c72-432e-adb7-7e0d85690849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t']/parent::*</value>
      <webElementGuid>2f628335-07ae-4207-850f-cc7352034b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/textarea</value>
      <webElementGuid>ce1a6828-bc4d-4796-9fe6-db9e3d21a17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit-checkitem-693127dc8d0c95d7420d2a2f' and (text() = 't' or . = 't')]</value>
      <webElementGuid>e12ff1fe-db0e-4cc6-8d4e-90c79dcc5618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
