<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apr 23, 2025, 1151 PM_APu9_M1MYhkJun_62530c</name>
   <tag></tag>
   <elementGuidId>a65e835e-eddb-4207-b603-49dd3bdfa555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.GuShmlgQU24O2r.f4L8hdFI5mPAUb.dBn9BtCLFJgCHA > div.E5Al1WuMnZSnCa > div > button.APu9_M1MYhkJun.Nv8oAmNcmfqNc4.ybVBgfOiuWZJtD.mUpWqmjL4CZBvn.Y8VSmRstKSzhJH._St8_YSRMkLv07</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[91]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9f42127-d609-4d84-8e12-054ec9fc8379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>APu9_M1MYhkJun Nv8oAmNcmfqNc4 ybVBgfOiuWZJtD mUpWqmjL4CZBvn Y8VSmRstKSzhJH _St8_YSRMkLv07</value>
      <webElementGuid>aa101853-acb0-4337-907c-cc78cad0ef83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8665d410-25b1-4d82-aef0-c4976891e1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89c87f6a-9e11-4428-afa4-fd67cf81f547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Power-ups</value>
      <webElementGuid>af2b10cb-315a-4a78-a4f1-5d02efaa9fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>064945c1-c222-4564-879f-8711ce6f5090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>170val-tooltip</value>
      <webElementGuid>bc17f96d-b9bd-4144-85a7-28aa8c70baa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Power-ups</value>
      <webElementGuid>849db107-2991-4259-a893-be89ccaa95f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-card-back&quot;)/div[@class=&quot;NU3Yu9KTws207g YPtsgaEOeBFV2L&quot;]/div[@class=&quot;uIImyziS34erOZ&quot;]/div[2]/div[@class=&quot;mqI1p85XmC2MaW BvYMUSHQ3VZhSV gVKBv3Rn1WqlNF udR7hhdNKnONkc GEdu4Dn5rTEUDE&quot;]/div[@class=&quot;cMcSJ6d3jjVbP6&quot;]/div[@class=&quot;FntQZvNq2QvxQL&quot;]/nav[@class=&quot;GuShmlgQU24O2r f4L8hdFI5mPAUb dBn9BtCLFJgCHA&quot;]/div[@class=&quot;E5Al1WuMnZSnCa&quot;]/div[1]/button[@class=&quot;APu9_M1MYhkJun Nv8oAmNcmfqNc4 ybVBgfOiuWZJtD mUpWqmjL4CZBvn Y8VSmRstKSzhJH _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>11f34be2-0da2-48dc-a1b6-4589f04b3aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[91]</value>
      <webElementGuid>8dc970d2-b65b-4790-9b4c-9571faa26211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/nav/div/div/button</value>
      <webElementGuid>a6417ca8-47f5-4095-8592-81a7599c628f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr 23, 2025, 11:51 PM'])[1]/following::button[2]</value>
      <webElementGuid>bf87a2a9-e380-46a4-b0ce-3e6c19f31865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặng Anh Nguyên'])[3]/following::button[2]</value>
      <webElementGuid>94f09d30-a578-42c5-9e25-1219693d14e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Power-ups'])[2]/preceding::button[1]</value>
      <webElementGuid>a04f626a-1250-49f3-8650-f969fbfe2731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/nav/div/div/button</value>
      <webElementGuid>3b41e1d0-29ab-46cd-bac0-77ba3c5a4a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Power-ups' or . = 'Power-ups')]</value>
      <webElementGuid>390a9f20-2d8c-4c71-be0b-55117993c994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
