<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Description_ak-editor-textarea</name>
   <tag></tag>
   <elementGuidId>20837671-c4bc-4d67-9a96-bed467732bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ak-editor-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ak-editor-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b5b504e-b969-47e2-85bf-6ecd4c3b4365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProseMirror ua-chrome ProseMirror-focused</value>
      <webElementGuid>4b4021b4-bcc5-4f9f-9a3b-164cd505fb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>2c51bf0e-9330-412d-bd1c-8347c383e177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01821568-94a1-4f2a-9114-d40516641dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ccf9a30e-d4a6-45fa-bcc9-a12c4c92b2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ak-editor-textarea</value>
      <webElementGuid>a9a1ce19-22bb-4d54-9f3f-a7f19695a06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-editor-id</name>
      <type>Main</type>
      <value>cec6f87f-5c2a-48cd-aebd-54ca4954705e</value>
      <webElementGuid>1e103545-15be-408d-ba4a-41f07b23f49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vc-ignore-if-no-layout-shift</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82e07be8-ebd0-4c62-8c62-c71781f8b6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03845421-cdcb-44c7-b616-d9c6275b7f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7100e84-9594-42d0-bad8-239e63a1a7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>693135c3-3568-46dd-abac-46360463847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ak-editor-textarea&quot;)</value>
      <webElementGuid>f4c99751-3052-4ca2-a0ac-2cd250962c71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ak-editor-textarea']</value>
      <webElementGuid>ace6bb6b-9ef9-4677-9a1b-08e8685eaa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-card-back']/div/div/div[2]/div/div/div/div[2]/main/div/section[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>86f8f1b4-543b-4ed2-9fda-bd1a2481853f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[74]</value>
      <webElementGuid>4fdcf056-f503-432e-bb0e-6df12df7d7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[1]/following::div[77]</value>
      <webElementGuid>6d7f585c-3daf-4aac-94fa-96cde17f0131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[2]</value>
      <webElementGuid>485253d6-5774-4894-bd4c-9f07a32dcfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[2]</value>
      <webElementGuid>fc77f06b-8946-4d84-963d-4c8207c2585b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]</value>
      <webElementGuid>2aa37d5b-889c-469a-9885-e76cfc85091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ak-editor-textarea']</value>
      <webElementGuid>ca990d88-e654-4bee-9f7b-2b90bdb518e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
