<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_rjY2KOSzslBciY (1)</name>
   <tag></tag>
   <elementGuidId>94ba9e70-cedb-433d-8650-d91a44f53dbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Demo_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.rjY2KOSzslBciY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52540f6c-f2c2-43d5-a6a6-6188222bfbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>board-name-input</value>
      <webElementGuid>07b6d526-c4b7-4f64-967d-79e4215a55c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rjY2KOSzslBciY</value>
      <webElementGuid>92abbe04-9338-450d-9ddf-29d8ee3e0a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Demo_1</value>
      <webElementGuid>c0daf810-50e2-459a-8b31-6c0964d6d401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trello-board-root&quot;)/div[1]/div[@class=&quot;board-wrapper&quot;]/div[@class=&quot;board-main-content MGBVHMvOK1TD8j Xpq6bBra11ICMi ivZ_wF4VZB8iYB&quot;]/div[@class=&quot;board-header u-clearfix js-board-header board-header-redesign-blur&quot;]/div[@class=&quot;Tp0C38uQUEpYUw&quot;]/span[@class=&quot;UyGARBfyjlePlW&quot;]/div[@class=&quot;yFR8tC0K4fD6K5 lWkxYS_6YVpYsA a_tCby5RhTa2g9&quot;]/input[@class=&quot;rjY2KOSzslBciY&quot;]</value>
      <webElementGuid>5fbce3f6-328d-46a8-ad52-10fcfaa3c493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Demo_1']</value>
      <webElementGuid>50dc934c-bdca-4118-9dfc-36f7f395d4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trello-board-root']/div/div/div/div[2]/div/span/div/input</value>
      <webElementGuid>e6f6c581-cb2c-4250-8e45-906cd3b85344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>1b53e68a-a275-455e-a309-48621c400a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
