<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0d5f9f5f-5a34-4264-a17c-f258ca87188a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-manager-discovery-ad']/div/div/div[2]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99cc2a13-611c-4919-9cbc-4fe58ba212d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/5853867a7cd123b1246e.png</value>
      <webElementGuid>d96efa31-c0e9-4d25-98f0-181a7d8379a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer-manager-discovery-ad&quot;)/div[@class=&quot;N5qD0z6tGXkHjM rAPmDzUNJMecQC lnxp8HPD2o2m9H&quot;]/div[@class=&quot;NyngjRUbMPoz8c&quot;]/div[@class=&quot;EbQqmcuE10uTP8&quot;]/div[@class=&quot;_ANOWYWgL0vt4n jhHd2LinHHaczY JUdMQ24Frx4eCF&quot;]/div[@class=&quot;gWGoXGb0bZ_lzA hQKwzDouajQQ2v jJJr8i6XRkk_Hf&quot;]/div[@class=&quot;uwVcleI2Z_w_Fn&quot;]/div[@class=&quot;myvXpKOD5zZSBB&quot;]/img[1]</value>
      <webElementGuid>4c78bc3b-83de-47f8-bfef-5bf5fe2e6cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer-manager-discovery-ad']/div/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>f491a938-6c98-4e4d-9ba8-1553753912d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ac2da2b1-8b9f-44cc-b35b-532bd4ba9fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/5853867a7cd123b1246e.png']</value>
      <webElementGuid>546b621c-b722-44ea-bde0-00e964577679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
