<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_date</name>
   <tag></tag>
   <elementGuidId>b2f806da-8e18-46f1-9687-4d77db383b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='date'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'N/T/NNNN' and @name = 'date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdae707a-fb9d-4fa4-b666-90451b6e20d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-textfield__input a3omnNx_j558kc a3omnNx_j558kc</value>
      <webElementGuid>7dfeadd0-f734-43f6-ad8c-2400d1933462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a2d78bc-7119-4d30-925e-9fdcc917a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>N/T/NNNN</value>
      <webElementGuid>90ba5587-d290-407a-9fba-8650e1906754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>due-date-field</value>
      <webElementGuid>34920339-4e43-418a-8a99-64b0e5e52fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>N/T/NNNN</value>
      <webElementGuid>3ee61233-f383-491e-b212-89dfb1d8f502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>77c69a74-f864-4dfa-a9ea-364b23677333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4/12/2025</value>
      <webElementGuid>a1c108d4-5ce3-494d-b505-4342f35774ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;feplat3731 react-overlay-up&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM YzL7yRijWxDng8&quot;]/div[1]/div[1]/form[1]/div[@class=&quot;Pn1tzZk3NgQPc8&quot;]/div[@class=&quot;VcKKqL2t6EWx1d&quot;]/div[@class=&quot;fzlccTmfltY2Sy&quot;]/fieldset[@class=&quot;NpF4lRNlrS2rVC&quot;]/div[@class=&quot;TMFD0fSgrnl0ez&quot;]/input[@class=&quot;nch-textfield__input a3omnNx_j558kc a3omnNx_j558kc&quot;]</value>
      <webElementGuid>9b9d0b2b-f57e-4d09-a4d8-aa3c06cbaa1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='date'])[2]</value>
      <webElementGuid>9b9ad526-6f0b-4ac0-8561-a3fca0a41492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/div/input</value>
      <webElementGuid>94be0ca7-1356-4511-9bb2-e546ee3c018c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'N/T/NNNN' and @name = 'date']</value>
      <webElementGuid>82caab1e-d1fd-4875-934e-f8971d97cc5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
