<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CurrentVisibility</name>
   <tag></tag>
   <elementGuidId>1acb40db-5086-4124-8004-e56b1a4378a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-testid='workspace-settings-visibility-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pabvJzVYb1kPsJ > button.ybVBgfOiuWZJtD._St8_YSRMkLv07</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>035f39fe-fc3d-4c94-9ea8-b16668f1fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ybVBgfOiuWZJtD _St8_YSRMkLv07</value>
      <webElementGuid>7fddd44b-f8fd-4ae1-b7e1-6d556ed13d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ff84e82-fc3a-4eb7-ade7-d989148b84d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>workspace-settings-visibility-button</value>
      <webElementGuid>f6f746dd-6a77-488e-8dff-be4ccdc5d160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Change workspace visibility</value>
      <webElementGuid>071ac963-6da8-4a6d-bfe5-e8bc9fd1da41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-only-warning</value>
      <webElementGuid>1a1dd4d3-174c-4d6c-a283-906f81043e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>4d2cd1c2-db39-4f90-a367-ab877f40e305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-react-root&quot;]/div[@class=&quot;gWf80FmcNO65Hd&quot;]/main[@class=&quot;hIlbOkoIOozQ23&quot;]/main[1]/div[@class=&quot;JxdNLDlN2aNNk3&quot;]/div[@class=&quot;GHlDfHJqcB_pQT&quot;]/div[@class=&quot;pabvJzVYb1kPsJ&quot;]/button[@class=&quot;ybVBgfOiuWZJtD _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>bccffd42-a651-4be9-b440-faa8e7c1f63b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>4dfee715-d622-4e5c-9239-3b08488994f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/main/main/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>34d607ff-c21a-47dd-983d-2472b746a13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workspace visibility'])[1]/following::button[1]</value>
      <webElementGuid>6966fd18-d52a-41cc-a963-98c5ac3c00a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::button[1]</value>
      <webElementGuid>6102013f-4734-4631-a276-922c24f863e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slack workspaces linking'])[1]/preceding::button[1]</value>
      <webElementGuid>46b6b4d3-9d6f-4f39-965d-d3f0e2c25538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more.'])[1]/preceding::button[1]</value>
      <webElementGuid>2a857eb7-e0e6-4b00-b3fc-b66242425261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>c2e62661-e082-4631-ac76-87c10646306f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>569a5007-2b31-474f-a88e-ed42b757ac1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>b57af628-2174-439c-9dfb-ed3956dbad5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
