<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ang lm_Ns0Sj0nEGMQ7un</name>
   <tag></tag>
   <elementGuidId>5a6ad17f-22e9-4eac-afbc-9a03c6d5b6aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a76c6a9-244b-4d07-b8cb-e20f98dc2515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93db4227-2ea7-4985-9f48-92ae647b0863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ns0Sj0nEGMQ7un</value>
      <webElementGuid>a4c529dd-a059-47c5-8bae-f660437b3425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>96b70008-0455-404b-b3ec-2b2a31db4e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/0BHIJzSR/11-tc1</value>
      <webElementGuid>7cb7f8c6-3d15-40fc-bc1c-65eaec8afe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-name</value>
      <webElementGuid>dd7ce0cc-0d9e-4ebc-9a51-e91e4db50158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tc1</value>
      <webElementGuid>f25e80cd-4308-40f3-8eff-2e73d33c401b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LBbj8Ff4qXPj8l&quot;]/div[@class=&quot;NYIHAreWw6Ga8y kCaocI3DJaoQ38&quot;]/span[@class=&quot;WpBdHiAP8hTeQK OZOw_0q9XfR1sR&quot;]/a[@class=&quot;Ns0Sj0nEGMQ7un&quot;]</value>
      <webElementGuid>636fde75-8947-4c1c-be01-900de8a1aa7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      <webElementGuid>9e050122-e8b0-4b88-a6be-5a4ae1b2f079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'tc1')])[3]</value>
      <webElementGuid>7b60d275-e33e-4021-ac50-e070bb93f264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang làm'])[2]/following::a[1]</value>
      <webElementGuid>df6903f8-dbfe-4015-9f93-5b1e55d104db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang làm'])[1]/following::a[1]</value>
      <webElementGuid>9851e25e-3c5d-440b-89ab-a696912f887f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a card'])[2]/preceding::a[1]</value>
      <webElementGuid>aef1bcb1-c9dd-44ba-a55c-a5eee542c4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đã xong'])[1]/preceding::a[1]</value>
      <webElementGuid>3ab2726b-0777-4d92-aa51-993f970652cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/0BHIJzSR/11-tc1')]</value>
      <webElementGuid>fa0fd386-1813-4002-8b9b-f148a8b1e261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ol/li/div/div/div/div/span[2]/a</value>
      <webElementGuid>aa8c616a-4229-41a1-83f8-40a09991c83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/0BHIJzSR/11-tc1' and (text() = 'tc1' or . = 'tc1')]</value>
      <webElementGuid>51051070-7044-4cbd-a7cf-7a26cdde57f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
