<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cn lm_Ns0Sj0nEGMQ7un</name>
   <tag></tag>
   <elementGuidId>3ae3a442-c73e-4bca-bbb9-9a29efee1505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='board']/li/div/ol/li/div/div/div/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Ns0Sj0nEGMQ7un</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63521232-8b09-416a-a4f4-5086acf83ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d3e1ed5-7937-4f90-b3f6-561a2eb7d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ns0Sj0nEGMQ7un</value>
      <webElementGuid>defab7c5-44ed-4da1-877e-b029162e1399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a787267a-439d-4950-84d1-d682d1d19b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/eV7Lq2Zo/1-tc1</value>
      <webElementGuid>be26d0ba-ac28-4e8e-a568-da76979a5f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>card-name</value>
      <webElementGuid>a0deeaf3-1809-42ad-b456-ff8ef85a9767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tc1</value>
      <webElementGuid>0100120c-c0dc-469d-81fc-a7f78112d73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/li[@class=&quot;Iq1byT5o1KoAi6&quot;]/div[@class=&quot;cYogZfEaHc9LfO&quot;]/ol[@class=&quot;B27wN5INCjrQTV&quot;]/li[@class=&quot;csCxU7M5teCNNl&quot;]/div[@class=&quot;PPk42xVXm4ipq3&quot;]/div[@class=&quot;z1bjoUSvJd2OG5&quot;]/div[@class=&quot;LBbj8Ff4qXPj8l&quot;]/div[@class=&quot;NYIHAreWw6Ga8y kCaocI3DJaoQ38&quot;]/span[@class=&quot;WpBdHiAP8hTeQK OZOw_0q9XfR1sR&quot;]/a[@class=&quot;Ns0Sj0nEGMQ7un&quot;]</value>
      <webElementGuid>c28acc03-3780-4c84-8a48-12b678fc4d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='board']/li/div/ol/li/div/div/div/div/span[2]/a</value>
      <webElementGuid>883511fc-b8c7-4cde-a524-e7f7117444b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'tc1')]</value>
      <webElementGuid>6f29c261-cfc3-4219-8ae3-e85ec0f6b693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cần làm'])[2]/following::a[1]</value>
      <webElementGuid>6260cb00-063c-42ae-9e32-8ab24d6b1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cần làm'])[1]/following::a[1]</value>
      <webElementGuid>e6b87658-76a8-4d5b-b0af-f84d0b3d4539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tc2'])[1]/preceding::a[1]</value>
      <webElementGuid>a66409bd-936f-43bb-9a32-2d9d1fbf2b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tc3'])[1]/preceding::a[2]</value>
      <webElementGuid>38f894cb-1a62-49f4-b8e5-46e2e360185d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tc1']/parent::*</value>
      <webElementGuid>14cd7bc9-881b-4b79-9658-d2897907dbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/eV7Lq2Zo/1-tc1')]</value>
      <webElementGuid>22fb15ce-b5c5-49f8-9bd1-6979d11799c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>23da109f-1c8a-4c6c-be47-7b0c2bd0b67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/eV7Lq2Zo/1-tc1' and (text() = 'tc1' or . = 'tc1')]</value>
      <webElementGuid>c1895c84-5aa6-4204-ba93-099a8913c570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
