<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__UM2HZR3yrq_M3h ybVBgfOiuWZJtD _St8__651e32 (1)</name>
   <tag></tag>
   <elementGuidId>26206c2f-a791-4d45-91c3-61824cb20015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > button.UM2HZR3yrq_M3h.ybVBgfOiuWZJtD._St8_YSRMkLv07</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e53eb70-d8b4-4cf6-8cce-a03f6ead6140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UM2HZR3yrq_M3h ybVBgfOiuWZJtD _St8_YSRMkLv07</value>
      <webElementGuid>c903009e-b74c-4a11-8449-a214874f7f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6970e575-5acd-4c3e-a846-9aa18b92dce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>board-background-select-gradient-gradient-ocean</value>
      <webElementGuid>f648bdcd-e405-42fc-a04a-ea10ce407c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dark blue gradient</value>
      <webElementGuid>f5ee8146-5dcd-4b63-af36-bb3c54dbdbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e5ed0825-0f4f-4e06-bb77-0da213643a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f993bed9-c202-4f7b-adbb-92cb8b52434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🌊</value>
      <webElementGuid>23a76228-5eb3-4ed9-a810-73ed9741f31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;feplat3731&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;Tu0XvZVffeyqqw _9gVZKx4ZK5x4I js-react-root&quot;]/div[2]/div[1]/div[@class=&quot;aFGD9vtcIAqeiM BxnW01nt1ospt1 YzL7yRijWxDng8&quot;]/div[@class=&quot;rdF_CdqSD31pjK&quot;]/section[@class=&quot;mgn8Z23aXE6pCQ&quot;]/div[1]/ul[@class=&quot;efjIYqeUA2_bHa&quot;]/li[3]/button[@class=&quot;UM2HZR3yrq_M3h ybVBgfOiuWZJtD _St8_YSRMkLv07&quot;]</value>
      <webElementGuid>fd884798-8c26-4229-8bf3-f88b64b9fc8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>5d4ca27f-835f-4fbf-9a83-96a59888d6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❄️'])[1]/following::button[1]</value>
      <webElementGuid>502c13f0-154f-4834-8fb5-99e8e791006a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🫧'])[1]/following::button[2]</value>
      <webElementGuid>10d48cb6-b4dd-4d78-ba76-828ddcbd681b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🔮'])[1]/preceding::button[1]</value>
      <webElementGuid>75581c09-e625-440d-ab70-f52a5fa25801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>f1145173-0bdf-439d-98cf-c3e74a78d4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '🌊' or . = '🌊')]</value>
      <webElementGuid>f25a0f51-72f5-4db9-8fa3-1025e02c2d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
