<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in with email_google-auth-button</name>
   <tag></tag>
   <elementGuidId>af419d7d-17b9-48f0-9ad2-5f94723f2131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#google-auth-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='google-auth-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9665b567-8d38-4dad-be0e-35786ac27462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google-auth-button</value>
      <webElementGuid>12b1f620-211a-4daf-b562-14b8ecae1672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1914zty</value>
      <webElementGuid>7a770ef2-325d-49c0-b0f6-c90c5166ff6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f6c7c3c-8e77-4be3-af2a-ece3d20badcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>deb5716e-bf4e-4b81-8487-b86cd46a6220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>909aac65-7da8-4844-bc64-fc9ab18c5f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google-auth-button&quot;)</value>
      <webElementGuid>e759d581-32bc-418a-b209-68ef9410d273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='google-auth-button']</value>
      <webElementGuid>ab1f9e36-0647-4cce-b3c7-6f68e7be506b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WhiteboxContainer']/div/section/ul/div/li/button</value>
      <webElementGuid>71d19860-c4ee-481b-b0b4-ce6f3d727e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with email'])[1]/following::button[1]</value>
      <webElementGuid>1f756f5d-5c9c-4b6c-9212-6ba3b6f66487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::button[2]</value>
      <webElementGuid>1e7b00c4-4e1b-41cb-bc1d-27667b6ff771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft'])[1]/preceding::button[1]</value>
      <webElementGuid>06f5b02b-825e-4f80-8c10-2e90b08970d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>045df8e8-2432-4869-bb3d-1363030abd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'google-auth-button' and @type = 'button' and (text() = 'Google' or . = 'Google')]</value>
      <webElementGuid>52104986-f4d8-494f-9c60-6776ad67ba2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
