<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>61124ff1-b558-4474-9682-dad655f13278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='google-auth-button']/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cafec350-bd5d-4f30-b661-501db90d17ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://id-frontend.prod-east.frontend.public.atl-paas.net/assets/google-logo.5867462c.svg</value>
      <webElementGuid>2bf7ed7d-5991-4440-ba88-7a296bd96b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google-auth-button&quot;)/span[@class=&quot;css-7xst2f&quot;]/img[1]</value>
      <webElementGuid>3aae143c-49f9-4f3e-bdd8-f2aa00e11b89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='google-auth-button']/span/img</value>
      <webElementGuid>a0d0c4d3-3a05-4645-a943-11cbedf143a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://id-frontend.prod-east.frontend.public.atl-paas.net/assets/google-logo.5867462c.svg')]</value>
      <webElementGuid>e8284873-e30d-4123-97ad-8fe117fccfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>76fadfc9-55bd-430d-9ff5-5bf20c38a79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://id-frontend.prod-east.frontend.public.atl-paas.net/assets/google-logo.5867462c.svg']</value>
      <webElementGuid>8029f360-9dae-4889-87bc-cdcabd031ba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
